#!/usr/bin/env node
const { spawnSync } = require('child_process');
const path = require('path');

const root = path.resolve(__dirname, '..');

function nodeCmd(script, ...args) {
  return { command: process.execPath, args: [script, ...args], label: ['node', script, ...args].join(' ') };
}

const GROUPS = Object.freeze({
  quick: Object.freeze([
    nodeCmd('tools/checks/docs-consolidation-smoke.js'),
    nodeCmd('tools/checks/version-toast-smoke.js'),
    nodeCmd('tools/checks/theme-shortcut-safe-area-polish-smoke.js'),
    nodeCmd('tools/checks/skeleton-ui-smoke.js'),
    nodeCmd('tools/checks/csp-inline-script-smoke.js'),
    nodeCmd('tools/checks/csp-inline-style-smoke.js'),
    nodeCmd('tools/checks/csp-style-src-hardening-smoke.js'),
    nodeCmd('tools/checks/deployment-guide-smoke.js'),
    nodeCmd('tools/checks/operations-docs-smoke.js'),
    nodeCmd('tools/checks/user-login-routing-smoke.js'),
    nodeCmd('tools/checks/user-state-namespace-smoke.js'),
    nodeCmd('tools/checks/multi-user-account-api-smoke.js'),
    nodeCmd('tools/checks/admin-user-management-ui-smoke.js'),
    nodeCmd('tools/checks/folder-mutation-permission-smoke.js'),
    nodeCmd('tools/checks/admin-sectioned-ui-smoke.js'),
    nodeCmd('tools/checks/admin-library-tree-smoke.js'),
    nodeCmd('tools/checks/owner-console-routing-smoke.js'),
    nodeCmd('tools/checks/library-access-folder-prefix-smoke.js'),
    nodeCmd('tools/checks/library-api-acl-smoke.js'),
    nodeCmd('tools/checks/owner-api-boundary-smoke.js'),
    nodeCmd('tools/checks/admin-library-preview-smoke.js'),
    nodeCmd('tools/checks/user-access-snapshot-cache-purge-smoke.js'),
    nodeCmd('tools/checks/font-owner-boundary-smoke.js'),
    nodeCmd('tools/checks/font-user-scope-smoke.js'),
    nodeCmd('tools/checks/multi-user-isolation-boundary-smoke.js'),
    nodeCmd('tools/checks/personal-data-isolation-doc-smoke.js'),
    nodeCmd('tools/checks/font-account-scope-ui-smoke.js'),
    nodeCmd('tools/checks/admin-user-state-management-smoke.js'),
    nodeCmd('tools/checks/admin-user-state-snapshot-smoke.js'),
    nodeCmd('tools/checks/user-state-snapshot-retention-smoke.js'),
    nodeCmd('tools/checks/admin-user-delete-policy-smoke.js'),
    nodeCmd('tools/checks/admin-user-session-revoke-smoke.js'),
    nodeCmd('tools/checks/audit-log-service-smoke.js'),
    nodeCmd('tools/checks/audit-log-query-smoke.js'),
    nodeCmd('tools/checks/audit-log-retention-smoke.js'),
    nodeCmd('tools/checks/admin-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-operational-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-preflight-ui-smoke.js'),
    nodeCmd('tools/checks/admin-js-deeper-split-smoke.js'),
    nodeCmd('tools/checks/admin-user-actions-split-smoke.js'),
    nodeCmd('tools/checks/admin-signup-audit-actions-split-smoke.js'),
    nodeCmd('tools/checks/admin-ops-detail-table-smoke.js'),
    nodeCmd('tools/checks/admin-state-actions-split-smoke.js'),
    nodeCmd('tools/checks/admin-permission-actions-split-smoke.js'),
    nodeCmd('tools/checks/admin-diagnostics-filter-smoke.js'),
    nodeCmd('tools/checks/admin-dead-code-after-split-smoke.js'),
    nodeCmd('tools/checks/release-verify-with-server-smoke.js'),
    nodeCmd('tools/checks/recovery-center-compact-ui-smoke.js'),
    nodeCmd('tools/checks/recovery-unused-files-pruned-smoke.js'),
    nodeCmd('tools/checks/recovery-status-actionable-badge-smoke.js'),
    nodeCmd('tools/checks/recovery-reader-stale-cache-summary-smoke.js'),
    nodeCmd('tools/checks/admin-ops-card-details-smoke.js'),
    nodeCmd('tools/checks/admin-ops-diagnostics-readability-smoke.js'),
    nodeCmd('tools/checks/security-hardening-v530-smoke.js'),
    nodeCmd('tools/checks/security-hardening-v531-smoke.js'),
    nodeCmd('tools/checks/security-hardening-v535-smoke.js'),
    nodeCmd('tools/checks/package-lock-regular-file-smoke.js'),
    nodeCmd('tools/checks/package-lock-public-registry-smoke.js'),
    nodeCmd('tools/checks/site-language-pack-bundle-smoke.js'),
    nodeCmd('tools/checks/site-language-bundle-fallback-smoke.js'),
    nodeCmd('tools/checks/site-shared-language-packs-smoke.js'),
    nodeCmd('tools/checks/site-custom-language-settings-smoke.js'),
    nodeCmd('tools/checks/admin-diagnostics-history-smoke.js'),
    nodeCmd('tools/checks/admin-access-preview-compare-smoke.js'),
    nodeCmd('tools/checks/signup-code-register-smoke.js'),
    nodeCmd('tools/checks/signup-code-atomic-smoke.js'),
    nodeCmd('tools/checks/account-password-operations-smoke.js'),
    nodeCmd('tools/checks/search-cache-only-no-network-smoke.js'),
    nodeCmd('tools/checks/search-local-default-no-network-smoke.js'),
    nodeCmd('tools/checks/search-option-dead-code-smoke.js'),
    nodeCmd('tools/checks/search-worker-client-smoke.js'),
    nodeCmd('tools/checks/search-worker-warm-start-smoke.js'),
    nodeCmd('tools/checks/search-worker-batch-smoke.js'),
    nodeCmd('tools/checks/search-worker-batch-schedule-smoke.js'),
    nodeCmd('tools/checks/search-full-scan-speed-smoke.js'),
    nodeCmd('tools/checks/search-server-load-mitigation-smoke.js'),
    nodeCmd('tools/checks/search-content-cache-limit-smoke.js'),
    nodeCmd('tools/checks/disk-cache-auto-prune-smoke.js'),
    nodeCmd('tools/checks/search-coverage-preview-schedule-smoke.js'),
    nodeCmd('tools/checks/search-modal-close-abort-smoke.js'),
    nodeCmd('tools/checks/search-cache-manifest-smoke.js'),
    nodeCmd('tools/checks/user-access-revoked-current-reader-smoke.js'),
    nodeCmd('tools/checks/account-password-hash-smoke.js'),
    nodeCmd('tools/checks/multi-user-design-doc-smoke.js'),
    nodeCmd('tools/checks/content-cache-rawtext-smoke.js'),
    nodeCmd('tools/checks/precompressed-static-smoke.js'),
    nodeCmd('tools/checks/precompressed-static-metadata-cache-smoke.js'),
    nodeCmd('tools/checks/precompressed-hash-smoke.js'),
    nodeCmd('tools/checks/modulepreload-entrypoints-smoke.js'),
    nodeCmd('tools/checks/versioned-rebuild-cache-smoke.js'),
    nodeCmd('tools/checks/block-manifest-conditional-cache-smoke.js'),
    nodeCmd('tools/checks/reader-api-conditional-cache-smoke.js'),
    nodeCmd('tools/checks/reader-api-cache-hardening-smoke.js'),
    nodeCmd('tools/checks/content-cache-io-diagnostics-smoke.js'),
    nodeCmd('tools/checks/content-worker-pool-abort-smoke.js'),
    nodeCmd('tools/checks/content-large-text-chunk-boundary-smoke.js'),
    nodeCmd('tools/checks/app-shell-force-cache-smoke.js'),
    nodeCmd('tools/checks/periodic-device-sync-dirty-check-smoke.js'),
    nodeCmd('tools/checks/content-large-file-chunk-cache-smoke.js'),
    nodeCmd('tools/checks/content-large-file-chunk-cache-hardening-smoke.js'),
    nodeCmd('tools/checks/block-manifest-disk-cache-smoke.js'),
    nodeCmd('tools/checks/block-manifest-folder-build-throttle-smoke.js'),
    nodeCmd('tools/checks/block-manifest-window-scope-smoke.js'),
    nodeCmd('tools/checks/block-manifest-episode-disk-cache-smoke.js'),
    nodeCmd('tools/checks/block-manifest-stable-etag-smoke.js'),
    nodeCmd('tools/checks/block-manifest-signature-invalidation-smoke.js'),
    nodeCmd('tools/checks/admin-io-diagnostics-table-smoke.js'),
    nodeCmd('tools/checks/reader-api-cold-warm-cache-smoke.js'),
    nodeCmd('tools/checks/cache-strategy-adjustment-smoke.js'),
    nodeCmd('tools/checks/admin-owner-css-split-review-smoke.js'),
    nodeCmd('tools/checks/css-html-boundary-contract-smoke.js'),
    nodeCmd('tools/checks/modulepreload-cache-policy-boundary-smoke.js'),
    nodeCmd('tools/checks/owner-session-entry-redirect-smoke.js'),
    nodeCmd('tools/checks/owner-session-reader-shell-redirect-smoke.js'),
    nodeCmd('tools/checks/owner-admin-routing-v470-smoke.js'),
    nodeCmd('tools/checks/deployed-cache-header-script-smoke.js'),
    nodeCmd('tools/checks/cache-invalidation-contract-smoke.js'),
    nodeCmd('tools/checks/cache-metrics-threshold-diagnostics-smoke.js'),
    nodeCmd('tools/checks/disk-cache-auto-prune-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-body-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-anchor-trace-export-smoke.js'),
    nodeCmd('tools/checks/reader-anchor-trace-low-overhead-smoke.js'),
    nodeCmd('tools/checks/reader-body-anchor-inertia-retain-smoke.js'),
    nodeCmd('tools/checks/reader-inertia-fixture-expansion-smoke.js'),
    nodeCmd('tools/checks/reader-anchor-regression-report-smoke.js'),
    nodeCmd('tools/checks/reader-safe-area-body-progress-smoke.js'),
    nodeCmd('tools/checks/reader-progress-dataset-guard-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-progress-stability-smoke.js'),
    nodeCmd('tools/checks/reader-buffer-append-current-chunk-retain-smoke.js'),
    nodeCmd('tools/checks/reader-progress-manifest-adoption-guard-smoke.js'),
    nodeCmd('tools/checks/reader-multifile-90-manifest-hold-smoke.js'),
    nodeCmd('tools/checks/reader-unified-append-restore-policy-smoke.js'),
    nodeCmd('tools/checks/reader-append-seam-70-85-progress-fixture-smoke.js'),
    nodeCmd('tools/checks/reader-append-inertia-damp-smoke.js'),
    nodeCmd('tools/checks/reader-ipad-touch-coast-retain-smoke.js'),
    nodeCmd('tools/checks/reader-ipad-touch-native-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-loaded-chunk-append-noop-smoke.js'),
    nodeCmd('tools/checks/reader-coordinate-eviction-smoke.js'),
    nodeCmd('tools/checks/reader-ipad-pseudo-fullscreen-smoke.js'),
    nodeCmd('tools/checks/reader-viewport-transition-anchor-smoke.js'),
    nodeCmd('tools/checks/library-catalog-performance-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-row-height-freeze-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-window-hold-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-anchor-restore-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-restore-decision-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-prefetch-window-smoke.js'),
    nodeCmd('tools/checks/novels-api-response-cache-budget-smoke.js'),
    nodeCmd('tools/checks/search-worker-warm-start-smoke.js'),
    nodeCmd('tools/checks/reader-row-measure-cache-diagnostics-smoke.js'),
    nodeCmd('tools/checks/reader-row-measured-margin-height-smoke.js'),
    nodeCmd('tools/checks/reader-actual-bottom-progress-trust-smoke.js'),
    nodeCmd('tools/checks/static-asset-preload-budget-smoke.js'),
    nodeCmd('tools/checks/current-version-lint-smoke.js'),
    nodeCmd('tools/checks/skeleton-timing-polish-smoke.js'),
    nodeCmd('tools/checks/skeleton-empty-state-guard-smoke.js'),
    nodeCmd('tools/checks/release-archive-backup-smoke.js'),
    nodeCmd('tools/checks/settings-connectivity-smoke.js'),
    nodeCmd('tools/checks/settings-account-ui-smoke.js'),
    nodeCmd('tools/checks/multi-file-progress-recent-smoke.js'),
    nodeCmd('tools/checks/library-multifile-disclosure-smoke.js'),
    nodeCmd('tools/checks/library-episode-volume-detection-smoke.js'),
    nodeCmd('tools/checks/pc-sidebar-close-toggle-smoke.js'),
    nodeCmd('tools/checks/site-responsive-sidebar-close-smoke.js'),
    nodeCmd('tools/checks/mobile-modal-layout-smoke.js'),
    nodeCmd('tools/check_server_structure.js')
  ]),
  docs: Object.freeze([
    nodeCmd('tools/checks/reader-anchoring-stability-contract-smoke.js'),
    nodeCmd('tools/checks/docs-consolidation-smoke.js'),
    nodeCmd('tools/checks/deployment-guide-smoke.js'),
    nodeCmd('tools/checks/operations-docs-smoke.js'),
    nodeCmd('tools/checks/version-toast-smoke.js')
  ]),
  cache: Object.freeze([
    nodeCmd('tools/checks/user-login-routing-smoke.js'),
    nodeCmd('tools/checks/user-state-namespace-smoke.js'),
    nodeCmd('tools/checks/multi-user-account-api-smoke.js'),
    nodeCmd('tools/checks/admin-user-management-ui-smoke.js'),
    nodeCmd('tools/checks/folder-mutation-permission-smoke.js'),
    nodeCmd('tools/checks/admin-library-tree-smoke.js'),
    nodeCmd('tools/checks/owner-console-routing-smoke.js'),
    nodeCmd('tools/checks/library-access-folder-prefix-smoke.js'),
    nodeCmd('tools/checks/library-api-acl-smoke.js'),
    nodeCmd('tools/checks/owner-api-boundary-smoke.js'),
    nodeCmd('tools/checks/admin-library-preview-smoke.js'),
    nodeCmd('tools/checks/user-access-snapshot-cache-purge-smoke.js'),
    nodeCmd('tools/checks/font-owner-boundary-smoke.js'),
    nodeCmd('tools/checks/font-user-scope-smoke.js'),
    nodeCmd('tools/checks/multi-user-isolation-boundary-smoke.js'),
    nodeCmd('tools/checks/personal-data-isolation-doc-smoke.js'),
    nodeCmd('tools/checks/font-account-scope-ui-smoke.js'),
    nodeCmd('tools/checks/admin-user-state-management-smoke.js'),
    nodeCmd('tools/checks/admin-user-state-snapshot-smoke.js'),
    nodeCmd('tools/checks/user-state-snapshot-retention-smoke.js'),
    nodeCmd('tools/checks/admin-user-delete-policy-smoke.js'),
    nodeCmd('tools/checks/admin-user-session-revoke-smoke.js'),
    nodeCmd('tools/checks/audit-log-service-smoke.js'),
    nodeCmd('tools/checks/audit-log-query-smoke.js'),
    nodeCmd('tools/checks/audit-log-retention-smoke.js'),
    nodeCmd('tools/checks/admin-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-operational-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-preflight-ui-smoke.js'),
    nodeCmd('tools/checks/admin-access-preview-compare-smoke.js'),
    nodeCmd('tools/checks/signup-code-register-smoke.js'),
    nodeCmd('tools/checks/signup-code-atomic-smoke.js'),
    nodeCmd('tools/checks/account-password-operations-smoke.js'),
    nodeCmd('tools/checks/user-access-revoked-current-reader-smoke.js'),
    nodeCmd('tools/checks/account-password-hash-smoke.js'),
    nodeCmd('tools/checks/multi-user-design-doc-smoke.js'),
    nodeCmd('tools/checks/content-cache-rawtext-smoke.js'),
    nodeCmd('tools/checks/search-cache-manifest-smoke.js'),
    nodeCmd('tools/checks/library-deep-signature-cache-smoke.js'),
    nodeCmd('tools/checks/precompressed-static-smoke.js'),
    nodeCmd('tools/checks/precompressed-static-metadata-cache-smoke.js'),
    nodeCmd('tools/checks/modulepreload-entrypoints-smoke.js'),
    nodeCmd('tools/checks/versioned-rebuild-cache-smoke.js'),
    nodeCmd('tools/checks/block-manifest-conditional-cache-smoke.js'),
    nodeCmd('tools/checks/reader-api-conditional-cache-smoke.js'),
    nodeCmd('tools/checks/reader-api-cache-hardening-smoke.js'),
    nodeCmd('tools/checks/content-cache-io-diagnostics-smoke.js'),
    nodeCmd('tools/checks/content-worker-pool-abort-smoke.js'),
    nodeCmd('tools/checks/content-large-text-chunk-boundary-smoke.js'),
    nodeCmd('tools/checks/app-shell-force-cache-smoke.js'),
    nodeCmd('tools/checks/periodic-device-sync-dirty-check-smoke.js'),
    nodeCmd('tools/checks/content-large-file-chunk-cache-smoke.js'),
    nodeCmd('tools/checks/content-large-file-chunk-cache-hardening-smoke.js'),
    nodeCmd('tools/checks/block-manifest-disk-cache-smoke.js'),
    nodeCmd('tools/checks/block-manifest-folder-build-throttle-smoke.js'),
    nodeCmd('tools/checks/block-manifest-window-scope-smoke.js'),
    nodeCmd('tools/checks/block-manifest-episode-disk-cache-smoke.js'),
    nodeCmd('tools/checks/block-manifest-stable-etag-smoke.js'),
    nodeCmd('tools/checks/block-manifest-signature-invalidation-smoke.js'),
    nodeCmd('tools/checks/admin-io-diagnostics-table-smoke.js'),
    nodeCmd('tools/checks/reader-api-cold-warm-cache-smoke.js'),
    nodeCmd('tools/checks/cache-strategy-adjustment-smoke.js'),
    nodeCmd('tools/checks/admin-owner-css-split-review-smoke.js'),
    nodeCmd('tools/checks/css-html-boundary-contract-smoke.js'),
    nodeCmd('tools/checks/modulepreload-cache-policy-boundary-smoke.js'),
    nodeCmd('tools/checks/owner-session-entry-redirect-smoke.js'),
    nodeCmd('tools/checks/owner-session-reader-shell-redirect-smoke.js'),
    nodeCmd('tools/checks/owner-admin-routing-v470-smoke.js'),
    nodeCmd('tools/checks/deployed-cache-header-script-smoke.js'),
    nodeCmd('tools/checks/cache-invalidation-contract-smoke.js'),
    nodeCmd('tools/checks/cache-metrics-threshold-diagnostics-smoke.js'),
    nodeCmd('tools/checks/disk-cache-auto-prune-smoke.js'),
    nodeCmd('tools/checks/library-catalog-performance-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-row-height-freeze-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-window-hold-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-anchor-restore-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-restore-decision-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-prefetch-window-smoke.js'),
    nodeCmd('tools/checks/novels-api-response-cache-budget-smoke.js'),
    nodeCmd('tools/checks/static-asset-preload-budget-smoke.js')
  ]),
  security: Object.freeze([
    nodeCmd('tools/checks/session-cookie-host-prefix-smoke.js'),
    nodeCmd('tools/checks/production-password-policy-smoke.js'),
    nodeCmd('tools/checks/custom-css-security-smoke.js'),
    nodeCmd('tools/checks/security-headers-smoke.js'),
    nodeCmd('tools/checks/csp-inline-script-smoke.js'),
    nodeCmd('tools/checks/csp-inline-style-smoke.js'),
    nodeCmd('tools/checks/csp-style-src-hardening-smoke.js'),
    nodeCmd('tools/checks/public-asset-allowlist-smoke.js'),
    nodeCmd('tools/checks/strict-origin-fetch-metadata-smoke.js'),
    nodeCmd('tools/checks/fileops-confirmation-smoke.js'),
    nodeCmd('tools/checks/rate-limit-prune-smoke.js'),
    nodeCmd('tools/checks/login-origin-healthz-smoke.js'),
    nodeCmd('tools/checks/login-session-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-cloudflare-visitor-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-cloudflare-tunnel-exposure-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-ops-diagnostics-readability-smoke.js'),
    nodeCmd('tools/checks/security-hardening-v530-smoke.js'),
    nodeCmd('tools/checks/security-hardening-v531-smoke.js'),
    nodeCmd('tools/checks/security-hardening-v535-smoke.js'),
    nodeCmd('tools/checks/font-owner-boundary-smoke.js'),
    nodeCmd('tools/checks/font-user-scope-smoke.js'),
    nodeCmd('tools/checks/multi-user-isolation-boundary-smoke.js'),
    nodeCmd('tools/checks/personal-data-isolation-doc-smoke.js'),
    nodeCmd('tools/checks/font-account-scope-ui-smoke.js'),
    nodeCmd('tools/checks/admin-user-session-revoke-smoke.js'),
    nodeCmd('tools/checks/audit-log-service-smoke.js'),
    nodeCmd('tools/checks/audit-log-query-smoke.js'),
    nodeCmd('tools/checks/audit-log-retention-smoke.js'),
    nodeCmd('tools/checks/admin-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-operational-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-preflight-ui-smoke.js'),
    nodeCmd('tools/checks/admin-access-preview-compare-smoke.js'),
    nodeCmd('tools/checks/signup-code-register-smoke.js'),
    nodeCmd('tools/checks/signup-code-atomic-smoke.js'),
    nodeCmd('tools/checks/account-password-operations-smoke.js'),
    nodeCmd('tools/checks/admin-user-state-snapshot-smoke.js'),
    nodeCmd('tools/checks/library-readonly-mutation-error-smoke.js'),
    nodeCmd('tools/checks/folder-mutation-permission-smoke.js')
  ]),
  reader: Object.freeze([
    nodeCmd('tools/checks/reader-anchoring-stability-contract-smoke.js'),
    nodeCmd('tools/checks/reader-append-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-multi-episode-append-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-scroll-buffer-patch-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-append-deferred-spacer-sync-smoke.js'),
    nodeCmd('tools/checks/reader-append-seam-render-smoke.js'),
    nodeCmd('tools/checks/reader-append-seam-anchor-correction-smoke.js'),
    nodeCmd('tools/checks/reader-append-seam-native-scroll-retain-smoke.js'),
    nodeCmd('tools/checks/reader-native-forward-scroll-retain-smoke.js'),
    nodeCmd('tools/checks/reader-native-forward-seam-transit-lock-smoke.js'),
    nodeCmd('tools/checks/reader-native-forward-seam-render-hold-smoke.js'),
    nodeCmd('tools/checks/reader-append-upward-correction-guard-smoke.js'),
    nodeCmd('tools/checks/reader-append-native-upward-retain-smoke.js'),
    nodeCmd('tools/checks/reader-append-correction-guard-smoke.js'),
    nodeCmd('tools/checks/reader-prune-exact-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-prune-prefix-delta-guard-smoke.js'),
    nodeCmd('tools/checks/reader-native-scroll-retain-smoke.js'),
    nodeCmd('tools/checks/reader-trusted-bottom-progress-smoke.js'),
    nodeCmd('tools/checks/reader-small-episode-chunk-boundary-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-body-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-anchor-trace-export-smoke.js'),
    nodeCmd('tools/checks/reader-anchor-trace-low-overhead-smoke.js'),
    nodeCmd('tools/checks/reader-body-anchor-inertia-retain-smoke.js'),
    nodeCmd('tools/checks/reader-inertia-fixture-expansion-smoke.js'),
    nodeCmd('tools/checks/reader-anchor-regression-report-smoke.js'),
    nodeCmd('tools/checks/reader-safe-area-body-progress-smoke.js'),
    nodeCmd('tools/checks/reader-progress-dataset-guard-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-progress-stability-smoke.js'),
    nodeCmd('tools/checks/reader-buffer-append-current-chunk-retain-smoke.js'),
    nodeCmd('tools/checks/reader-progress-manifest-adoption-guard-smoke.js'),
    nodeCmd('tools/checks/reader-multifile-90-manifest-hold-smoke.js'),
    nodeCmd('tools/checks/reader-unified-append-restore-policy-smoke.js'),
    nodeCmd('tools/checks/reader-append-seam-70-85-progress-fixture-smoke.js'),
    nodeCmd('tools/checks/reader-append-inertia-damp-smoke.js'),
    nodeCmd('tools/checks/reader-ipad-touch-coast-retain-smoke.js'),
    nodeCmd('tools/checks/reader-ipad-touch-native-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-loaded-chunk-append-noop-smoke.js'),
    nodeCmd('tools/checks/reader-ipad-pseudo-fullscreen-smoke.js'),
    nodeCmd('tools/checks/reader-viewport-transition-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-multifile-native-scroll-anchor-stabilization-smoke.js'),
    nodeCmd('tools/checks/reader-multifile-native-settle-exact-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-scroll-settle-exact-anchor-restore-smoke.js'),
    nodeCmd('tools/checks/reader-append-incremental-delta-layout-smoke.js'),
    nodeCmd('tools/checks/reader-row-measure-cache-diagnostics-smoke.js'),
    nodeCmd('tools/checks/reader-row-measured-margin-height-smoke.js'),
    nodeCmd('tools/checks/reader-actual-bottom-progress-trust-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-local-slider-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-slider-totalchunks-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-slider-dom-progress-smoke.js'),
    nodeCmd('tools/checks/reader-safe-area-multifile-progress-smoke.js'),
    nodeCmd('tools/checks/reader-multifile-resume-local-ratio-smoke.js'),
    nodeCmd('tools/checks/reader-coordinate-policy-v470-smoke.js'),
    nodeCmd('tools/checks/reader-prev-boundary-top-indicator-smoke.js'),
    nodeCmd('tools/checks/reader-slider-char-target-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-full-file-char-progress-direct-smoke.js'),
    nodeCmd('tools/checks/reader-coordinate-eviction-smoke.js'),
    nodeCmd('tools/checks/pill-status-samsung-pwa-inline-lock-removed-smoke.js'),
    nodeCmd('tools/checks/status-pill-fullscreen-compact-smoke.js'),
    nodeCmd('tools/checks/fullscreen-pill-safe-area-style-smoke.js'),
    nodeCmd('tools/checks/reader-bottom-ratio-boundary-lock-smoke.js'),
    nodeCmd('tools/checks/reader-episode-bottom-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-episode-boundary-mode-smoke.js'),
    nodeCmd('tools/checks/reader-jump-panel-episode-select-smoke.js'),
    nodeCmd('tools/checks/reader-native-scroll-settle-freeze-smoke.js'),
    nodeCmd('tools/checks/reader-nav-terminal-progress-sync-smoke.js'),
    nodeCmd('tools/checks/reader-nav-slider-release-commit-smoke.js'),
    nodeCmd('tools/checks/reader-nav-slider-anchor-offset-smoke.js'),
    nodeCmd('tools/checks/reader-nav-slider-in-window-jump-smoke.js'),
    nodeCmd('tools/checks/multi-file-progress-recent-smoke.js')
  ]),

  search: Object.freeze([
    nodeCmd('tools/checks/search-multi-episode-full-scan-smoke.js'),
    nodeCmd('tools/checks/search-v364-runtime-smoke.js'),
    nodeCmd('tools/checks/search-continue-during-navigation-smoke.js'),
    nodeCmd('tools/checks/search-compact-status-smoke.js'),
    nodeCmd('tools/checks/search-cache-only-no-network-smoke.js'),
    nodeCmd('tools/checks/search-local-default-no-network-smoke.js'),
    nodeCmd('tools/checks/search-worker-client-smoke.js'),
    nodeCmd('tools/checks/search-worker-warm-start-smoke.js'),
    nodeCmd('tools/checks/search-worker-batch-smoke.js'),
    nodeCmd('tools/checks/search-worker-batch-schedule-smoke.js'),
    nodeCmd('tools/checks/search-full-scan-speed-smoke.js'),
    nodeCmd('tools/checks/search-server-load-mitigation-smoke.js'),
    nodeCmd('tools/checks/search-content-cache-limit-smoke.js'),
    nodeCmd('tools/checks/search-coverage-preview-schedule-smoke.js'),
    nodeCmd('tools/checks/search-modal-close-abort-smoke.js'),
    nodeCmd('tools/checks/search-cache-manifest-smoke.js')
  ]),
  settings: Object.freeze([
    nodeCmd('tools/checks/settings-connectivity-smoke.js'),
    nodeCmd('tools/checks/settings-account-ui-smoke.js'),
    nodeCmd('tools/checks/site-language-bundle-fallback-smoke.js'),
    nodeCmd('tools/checks/site-custom-language-settings-smoke.js'),
    nodeCmd('tools/checks/settings-functional-controls-smoke.js'),
    nodeCmd('tools/checks/settings-reader-preset-buttons-smoke.js'),
    nodeCmd('tools/checks/pc-sidebar-close-toggle-smoke.js'),
    nodeCmd('tools/checks/site-responsive-sidebar-close-smoke.js'),
    nodeCmd('tools/checks/mobile-modal-layout-smoke.js'),
    nodeCmd('tools/checks/theme-shortcut-safe-area-polish-smoke.js')
  ]),
  frontend: Object.freeze([
    nodeCmd('tools/check_rebuild_frontend.js', '--quiet-ok'),
    nodeCmd('tools/check_frontend_supervisor.js', '--quiet-ok')
  ]),
  server: Object.freeze([
    nodeCmd('tools/check_server_structure.js'),
    nodeCmd('tools/smoke_server_http.js')
  ])
});

const COMPOSITE_GROUPS = Object.freeze({
  standard: Object.freeze([
    ...GROUPS.docs,
    ...GROUPS.cache,
    ...GROUPS.security,
    ...GROUPS.reader,
    ...GROUPS.search,
    ...GROUPS.settings,
    nodeCmd('tools/checks/library-multifile-disclosure-smoke.js'),
    nodeCmd('tools/checks/library-episode-volume-detection-smoke.js'),
    nodeCmd('tools/checks/pc-sidebar-close-toggle-smoke.js'),
    nodeCmd('tools/checks/site-responsive-sidebar-close-smoke.js'),
    nodeCmd('tools/checks/mobile-modal-layout-smoke.js'),
    nodeCmd('tools/check_server_structure.js'),
    nodeCmd('tools/smoke_server_http.js')
  ]),
  full: Object.freeze([
    ...GROUPS.docs,
    ...GROUPS.cache,
    ...GROUPS.security,
    ...GROUPS.reader,
    ...GROUPS.search,
    ...GROUPS.settings,
    ...GROUPS.server,
    ...GROUPS.frontend
  ])
});

const ALL_GROUPS = Object.freeze({ ...GROUPS, ...COMPOSITE_GROUPS });

function printUsage() {
  const groups = Object.keys(ALL_GROUPS).sort().map(name => `  --${name}`).join('\n');
  console.error(`Usage: node tools/run_smoke_tests.js --<group>\n\nGroups:\n${groups}`);
}

function parseGroup(argv) {
  const flags = argv.filter(arg => arg.startsWith('--'));
  if (flags.length !== 1) return null;
  const name = flags[0].slice(2);
  if (!Object.prototype.hasOwnProperty.call(ALL_GROUPS, name)) return null;
  if (argv.some(arg => !arg.startsWith('--'))) return null;
  return name;
}

function runCommand(task, index, total) {
  console.log(`\n[${index}/${total}] ${task.label}`);
  const result = spawnSync(task.command, task.args, {
    cwd: root,
    env: process.env,
    stdio: 'inherit',
    shell: false,
    windowsHide: true
  });
  if (result.error) {
    return { ok: false, command: task.label, error: result.error.message, status: result.status };
  }
  return { ok: result.status === 0, command: task.label, status: result.status };
}

function main() {
  const group = parseGroup(process.argv.slice(2));
  if (!group) {
    printUsage();
    process.exit(2);
  }
  const tasks = ALL_GROUPS[group];
  console.log(`Smoke runner group: ${group}`);
  const results = [];
  for (let i = 0; i < tasks.length; i += 1) {
    const result = runCommand(tasks[i], i + 1, tasks.length);
    results.push(result);
    if (!result.ok) break;
  }
  const passed = results.filter(result => result.ok).length;
  const failed = results.find(result => !result.ok);
  if (failed) {
    console.error(`\nSmoke runner failed: ${passed}/${tasks.length}`);
    console.error(`Failed command: ${failed.command}`);
    if (failed.error) console.error(`Error: ${failed.error}`);
    process.exit(failed.status || 1);
  }
  console.log(`\nSmoke runner passed: ${passed}/${tasks.length}`);
  process.exit(0);
}

main();
