#!/usr/bin/env node
const { spawnSync } = require('child_process');
const path = require('path');
const fs = require('fs');

const root = path.resolve(__dirname, '..');

function nodeCmd(script, ...args) {
  return { command: process.execPath, args: [script, ...args], label: ['node', script, ...args].join(' ') };
}

const GROUPS = Object.freeze({
  quick: Object.freeze([
    nodeCmd('tools/checks/release-verify-current-coverage-v682-smoke.js'),
    nodeCmd('tools/checks/v682-active-check-registration-smoke.js'),
    nodeCmd('tools/checks/v682-library-organization-powershell51-compat-smoke.js'),
    nodeCmd('tools/checks/v681-metadata-manual-provider-filter-smoke.js'),
    nodeCmd('tools/checks/release-verify-current-coverage-v680-smoke.js'),
    nodeCmd('tools/checks/v680-active-check-registration-smoke.js'),
    nodeCmd('tools/checks/v680-login-owner-palette-smoke.js'),
    nodeCmd('tools/checks/v680-user-theme-bootstrap-smoke.js'),
    nodeCmd('tools/checks/v680-theme-runtime-contract-smoke.js'),
    nodeCmd('tools/checks/v678-extension-popup-fixed-width-smoke.js'),
    nodeCmd('tools/checks/v678-extension-popup-narrow-layout-smoke.js'),
    nodeCmd('tools/checks/v678-metadata-folder-theme-smoke.js'),
    nodeCmd('tools/checks/v679-metadata-folder-disclosure-smoke.js'),
    nodeCmd('tools/checks/v677-metadata-hard-cap-incremental-smoke.js'),
    nodeCmd('tools/checks/v677-library-tree-folder-cursor-smoke.js'),
    nodeCmd('tools/checks/v677-cover-audit-nofollow-smoke.js'),
    nodeCmd('tools/checks/v677-package-format-parser-smoke.js'),
    nodeCmd('tools/checks/v677-runtime-dependency-install-smoke.js'),
    nodeCmd('tools/checks/v676-compose-environment-yaml-smoke.js'),
    nodeCmd('tools/checks/v676-trusted-proxy-validation-smoke.js'),
    nodeCmd('tools/checks/v676-metadata-bounded-resident-smoke.js'),
    nodeCmd('tools/checks/v676-reader-prefetch-orphan-circuit-smoke.mjs'),
    nodeCmd('tools/checks/v676-modal-stack-runtime-smoke.mjs'),
    nodeCmd('tools/checks/v676-font-io-error-propagation-smoke.js'),
    nodeCmd('tools/checks/v676-progress-journal-symlink-smoke.js'),
    nodeCmd('tools/checks/v676-extension-shortcut-responsive-smoke.js'),
    nodeCmd('tools/checks/v676-metadata-folder-continuity-smoke.mjs'),
    nodeCmd('tools/checks/v675-progress-delta-journal-smoke.js'),
    nodeCmd('tools/checks/v675-metadata-compact-index-smoke.js'),
    nodeCmd('tools/checks/v675-trusted-proxy-source-smoke.js'),
    nodeCmd('tools/checks/v675-reader-prefetch-watchdog-smoke.mjs'),
    nodeCmd('tools/checks/v675-service-worker-dual-failure-smoke.js'),
    nodeCmd('tools/checks/v675-font-symlink-boundary-smoke.js'),
    nodeCmd('tools/checks/v675-modal-focus-manager-smoke.mjs'),
    nodeCmd('tools/checks/v675-profile-skeleton-smoke.mjs'),
    nodeCmd('tools/checks/v674-progress-local-compaction-smoke.mjs'),
    nodeCmd('tools/checks/v674-reader-prefetch-cancel-race-smoke.mjs'),
    nodeCmd('tools/checks/v674-library-bounded-fallback-smoke.mjs'),
    nodeCmd('tools/checks/v674-service-worker-navigation-state-failure-smoke.js'),
    nodeCmd('tools/checks/v674-server-filesystem-durability-smoke.js'),
    nodeCmd('tools/checks/v674-server-device-profile-cap-smoke.js'),
    nodeCmd('tools/checks/v674-metadata-playwright-dns-pinning-smoke.js'),
    nodeCmd('tools/checks/v674-cross-platform-gate-contract-smoke.js'),
    nodeCmd('tools/checks/v673-metadata-applied-index-smoke.js'),
    nodeCmd('tools/checks/v673-metadata-applied-shard-smoke.js'),
    nodeCmd('tools/checks/v673-metadata-candidate-shard-race-smoke.js'),
    nodeCmd('tools/checks/v673-metadata-sparse-shard-init-smoke.js'),
    nodeCmd('tools/checks/v673-library-shelf-hot-path-smoke.js'),
    nodeCmd('tools/checks/v673-library-variant-coarse-bucket-smoke.js'),
    nodeCmd('tools/checks/v673-disk-cache-bounded-candidate-smoke.js'),
    nodeCmd('tools/checks/v672-metadata-cpu-optimization-smoke.js'),
    nodeCmd('tools/checks/v671-p0-p1-stability-smoke.js'),
    nodeCmd('tools/checks/metadata-provider-completion-cooldown-v669-smoke.js'),
    nodeCmd('tools/checks/v670-settings-language-advanced-smoke.mjs'),
    nodeCmd('tools/checks/v668-library-shell-isolation-smoke.mjs'),
    nodeCmd('tools/checks/v667-ui-metadata-provider-smoke.js'),
    nodeCmd('tools/checks/v666-non-auth-autofill-guard-smoke.js'),
    nodeCmd('tools/checks/v665-manual-cover-recognition-smoke.js'),
    nodeCmd('tools/checks/v665-node-direct-launch-smoke.js'),
    nodeCmd('tools/checks/v665-docs-consolidation-smoke.js'),
    nodeCmd('tools/checks/v664-library-resume-explorer-quick-smoke.mjs'),
    nodeCmd('tools/checks/v663-assets-csp-cover-smoke.mjs'),
    nodeCmd('tools/checks/v662-deferred-ui-530-recovery-smoke.mjs'),
    nodeCmd('tools/checks/v661-audit-fixes-env-docs-smoke.mjs'),
    nodeCmd('tools/checks/v660-read-data-reader-tabs-isolation-smoke.mjs'),
    nodeCmd('tools/checks/v659-settings-bindings-layout-smoke.mjs'),
    nodeCmd('tools/checks/v659-settings-actual-bindings-runtime.mjs'),
    nodeCmd('tools/checks/v658-settings-gesture-labels-smoke.mjs'),
    nodeCmd('tools/checks/v657-admin-settings-viewport-smoke.mjs'),
    nodeCmd('tools/checks/v656-mobile-explorer-settings-smoke.mjs'),
    nodeCmd('tools/checks/v655-library-settings-admin-ux-smoke.mjs'),
    nodeCmd('tools/checks/v654-settings-shelf-navigation-smoke.mjs'),
    nodeCmd('tools/checks/settings-library-tab-visibility-v653-smoke.mjs'),
    nodeCmd('tools/checks/library-mobile-header-reveal-v653-smoke.mjs'),
    nodeCmd('tools/checks/admin-owner-layout-smoke.js'),
    nodeCmd('tools/checks/admin-user-management-mobile-layout-smoke.js'),
    nodeCmd('tools/checks/settings-workspace-v652-smoke.mjs'),
    nodeCmd('tools/checks/admin-cleanup-summary-v651-smoke.mjs'),
    nodeCmd('tools/checks/reader-jump-percent-input-v652-smoke.mjs'),
    nodeCmd('tools/checks/admin-cleanup-summary-v651-smoke.mjs'),
    nodeCmd('tools/checks/update-banner-critical-v651-smoke.js'),
    nodeCmd('tools/checks/settings-page-state-v651-smoke.mjs'),
    nodeCmd('tools/checks/library-mutation-journal-v649-smoke.js'),
    nodeCmd('tools/checks/v649-audit-fixes-smoke.js'),
    nodeCmd('tools/checks/release-verify-timeout-v649-smoke.js'),
    nodeCmd('tools/checks/admin-responsive-permission-cleanup-v649-smoke.js'),
    nodeCmd('tools/checks/library-reader-settings-v650-smoke.mjs'),
    nodeCmd('tools/checks/reader-fullscreen-header-v650-smoke.mjs'),
    nodeCmd('tools/checks/metadata-manual-fast-path-v648-smoke.mjs'),
    nodeCmd('tools/checks/library-durable-invalidation-v648-smoke.js'),
    nodeCmd('tools/checks/library-request-boundary-v648-smoke.js'),
    nodeCmd('tools/checks/v648-audit-runtime-fixes-smoke.mjs'),
    nodeCmd('tools/checks/library-settings-diagnostics-v647-smoke.mjs'),
    nodeCmd('tools/checks/reader-search-modal-v647-smoke.js'),
    nodeCmd('tools/checks/library-stability-v646-smoke.js'),
    nodeCmd('tools/checks/library-request-resilience-v646-smoke.mjs'),
    nodeCmd('tools/checks/library-reader-ui-v645-smoke.js'),
    nodeCmd('tools/checks/network-search-mode-v645-smoke.js'),
    nodeCmd('tools/checks/deferred-ui-style-recovery-v645-smoke.js'),
    nodeCmd('tools/checks/library-mobile-header-v644-smoke.js'),
    nodeCmd('tools/checks/library-entry-load-budget-v644-smoke.mjs'),
    nodeCmd('tools/checks/owner-library-permission-ui-v643-smoke.js'),
    nodeCmd('tools/checks/owner-metadata-locale-settings-v643-smoke.js'),
    nodeCmd('tools/checks/metadata-provider-settings-v643-smoke.js'),
    nodeCmd('tools/checks/library-cleanup-candidates-v643-smoke.js'),
    nodeCmd('tools/checks/library-organization-v643-smoke.js'),
    nodeCmd('tools/checks/site-language-packs-v643-smoke.js'),
    nodeCmd('tools/checks/metadata-page-locale-v643-smoke.js'),
    nodeCmd('tools/checks/metadata-compressed-store-v642-smoke.js'),
    nodeCmd('tools/checks/metadata-candidate-maintenance-v642-smoke.js'),
    nodeCmd('tools/checks/metadata-storage-maintenance-ui-v642-smoke.js'),
    nodeCmd('tools/checks/library-metadata-content-grouping-v642-smoke.js'),
    nodeCmd('tools/checks/library-variant-relations-v642-smoke.js'),
    nodeCmd('tools/checks/library-variant-preference-v642-smoke.js'),
    nodeCmd('tools/checks/library-content-fingerprint-v642-smoke.js'),
    nodeCmd('tools/checks/library-content-discovery-v642-smoke.js'),
    nodeCmd('tools/checks/library-cleanup-similarity-ui-v642-smoke.js'),
    nodeCmd('tools/checks/library-grouping-runtime-wiring-v642-smoke.js'),
    nodeCmd('tools/checks/v641-audit-security-durability-smoke.js'),
    nodeCmd('tools/checks/v641-metadata-manual-clear-smoke.js'),
    nodeCmd('tools/checks/v641-owner-library-extension-smoke.js'),
    nodeCmd('tools/checks/v641-packaging-gates-smoke.js'),
    nodeCmd('tools/checks/source-size-budget-v641-smoke.js'),
    nodeCmd('tools/checks/version-contract-import-order-v641-smoke.js'),
    nodeCmd('tools/checks/package-inventory-exclude-v641-smoke.js'),
    nodeCmd('tools/checks/metadata-ssn-provider-v640-smoke.js'),
    nodeCmd('tools/checks/metadata-ssn-collection-v640-smoke.js'),
    nodeCmd('tools/checks/admin-owner-workspace-v640-smoke.js'),
    nodeCmd('tools/checks/login-public-assets-v639-smoke.js'),
    nodeCmd('tools/checks/metadata-equivalent-group-cover-v639-smoke.js'),
    nodeCmd('tools/checks/scroll-to-top-overlay-v639-smoke.js'),
    nodeCmd('tools/checks/login-silent-handshake-v638-smoke.js'),
    nodeCmd('tools/checks/service-worker-client-state-bounds-v638-smoke.js'),
    nodeCmd('tools/checks/metadata-manual-cover-legacy-v638-smoke.js'),
    nodeCmd('tools/checks/metadata-equivalent-candidate-groups-v638-smoke.js'),
    nodeCmd('tools/checks/scroll-to-top-v638-smoke.js'),
    nodeCmd('tools/checks/service-worker-client-state-v637-smoke.js'),
    nodeCmd('tools/checks/update-button-idempotency-v637-smoke.js'),
    nodeCmd('tools/checks/stale-executable-policy-v637-smoke.js'),
    nodeCmd('tools/checks/metadata-manual-cover-v637-smoke.js'),
    nodeCmd('tools/checks/service-worker-update-coordination-v636-smoke.js'),
    nodeCmd('tools/checks/metadata-cover-lease-durability-v636-smoke.js'),
    nodeCmd('tools/checks/service-worker-update-activation-v635-smoke.js'),
    nodeCmd('tools/checks/metadata-cover-update-safety-v635-smoke.js'),
    nodeCmd('tools/checks/metadata-novelpia-cover-v634-smoke.js'),
    nodeCmd('tools/checks/metadata-manual-cover-upload-v634-smoke.js'),
    nodeCmd('tools/checks/cdn-worker-stale-assets-v633-smoke.js'),
    nodeCmd('tools/checks/service-worker-cloudflare-v632-smoke.js'),
    nodeCmd('tools/checks/service-worker-forward-upgrade-v631-smoke.js'),
    nodeCmd('tools/checks/library-cleanup-ui-v630-smoke.js'),
    nodeCmd('tools/checks/metadata-manual-candidate-delete-v630-smoke.js'),
    nodeCmd('tools/checks/ui-build-badge-v629-smoke.js'),
    nodeCmd('tools/checks/library-cleanup-real-fixture-v628-smoke.js'),
    nodeCmd('tools/checks/library-cleanup-admin-route-v628-smoke.js'),
    nodeCmd('tools/checks/smoke-runner-command-timeout-v628-smoke.js'),
    nodeCmd('tools/checks/v627-reaudit-fixes-smoke.js'),
    nodeCmd('tools/checks/metadata-live-score-competition-v627-smoke.js'),
    nodeCmd('tools/checks/fileops-stale-lock-v627-smoke.js'),
    nodeCmd('tools/checks/ui-scrollbar-compose-v626-smoke.js'),
    nodeCmd('tools/checks/security-reaudit-v625-smoke.js'),
    nodeCmd('tools/checks/metadata-playwright-secure-fast-v625-smoke.js'),
    nodeCmd('tools/checks/metadata-performance-v625-smoke.js'),
    nodeCmd('tools/checks/responsive-pages-v624-smoke.js'),
    nodeCmd('tools/checks/metadata-job-poll-selection-v624-smoke.js'),
    nodeCmd('tools/checks/metadata-work-filters-v623-smoke.js'),
    nodeCmd('tools/checks/metadata-provider-mobile-v622-smoke.js'),
    nodeCmd('tools/checks/metadata-mobile-fallback-service-v622-smoke.js'),
    nodeCmd('tools/checks/metadata-munpia-current-v622-smoke.js'),
    nodeCmd('tools/checks/metadata-score-priority-bulk-apply-v619-smoke.js'),
    nodeCmd('tools/checks/metadata-novelpia-adult-playwright-v617-smoke.js'),
    nodeCmd('tools/checks/metadata-novelpia-adult-collection-v617-smoke.js'),
    nodeCmd('tools/checks/metadata-view-state-v616-smoke.js'),
    nodeCmd('tools/checks/ux-disruption-guard-v616-smoke.js'),
    nodeCmd('tools/checks/metadata-candidate-dedup-v615-smoke.js'),
    nodeCmd('tools/checks/modulepreload-entrypoints-smoke.js'),
    nodeCmd('tools/checks/access-bootstrap-v613-smoke.mjs'),
    nodeCmd('tools/checks/metadata-restart-resume-v614-smoke.js'),
    nodeCmd('tools/checks/metadata-auto-apply-v614-smoke.js'),
    nodeCmd('tools/checks/user-scoped-storage-v613-smoke.mjs'),
    nodeCmd('tools/checks/progress-user-scope-v613-smoke.mjs'),
    nodeCmd('tools/checks/reader-cache-user-scope-v613-smoke.mjs'),
    nodeCmd('tools/checks/progress-lifecycle-immediate-v613-smoke.mjs'),
    nodeCmd('tools/checks/critical-preload-budget-v613-smoke.js'),
    nodeCmd('tools/checks/ui-version-accessibility-v613-smoke.js'),
    nodeCmd('tools/checks/smoke-runner-dependency-block-v613-smoke.js'),
    nodeCmd('tools/checks/progress-delta-single-acl-v613-smoke.js'),
    nodeCmd('tools/checks/library-bridge-split-v301-smoke.js'),
    nodeCmd('tools/checks/library-runtime-bridge-split-v304-smoke.js'),
    nodeCmd('tools/checks/library-virtual-runtime-split-smoke.js'),
    nodeCmd('tools/checks/recovery-library-copy-payload-adapter-smoke.js'),
    nodeCmd('tools/checks/recovery-library-diagnostics-panel-split-v305-smoke.js'),
    nodeCmd('tools/checks/recovery-library-full-split-v307-smoke.js'),
    nodeCmd('tools/checks/recovery-library-manual-review-bundle-payload-split-v306-smoke.js'),
    nodeCmd('tools/checks/recovery-library-manual-review-context-smoke.js'),
    nodeCmd('tools/checks/recovery-library-virtual-payload-context-smoke.js'),
    nodeCmd('tools/checks/api-boundary-v611-smoke.js'),
    nodeCmd('tools/checks/progress-delta-v612-smoke.mjs'),
    nodeCmd('tools/checks/progress-storage-coalesce-v612-smoke.mjs'),
    nodeCmd('tools/checks/library-async-event-guard-v612-smoke.mjs'),
    nodeCmd('tools/checks/library-access-snapshot-v612-smoke.mjs'),
    nodeCmd('tools/checks/archive-safety-v611-smoke.js'),
    nodeCmd('tools/checks/deployment-probe-v611-smoke.js'),
    nodeCmd('tools/checks/package-archive-fallback-v610-smoke.js'),
    nodeCmd('tools/checks/async-route-v610-smoke.js'),
    nodeCmd('tools/checks/shutdown-contract-v610-smoke.js'),
    nodeCmd('tools/checks/deployment-state-boot-v610-smoke.js'),
    nodeCmd('tools/checks/font-sync-atomic-v610-smoke.js'),
    nodeCmd('tools/checks/json-backup-windows-fsync-v608-smoke.js'),
    nodeCmd('tools/checks/reader-race-ownership-v608-smoke.mjs'),
    nodeCmd('tools/checks/session-logout-durability-v606-smoke.js'),
    nodeCmd('tools/checks/login-session-durability-v606-smoke.js'),
    nodeCmd('tools/checks/content-worker-shutdown-v606-smoke.js'),
    nodeCmd('tools/checks/precompressed-http-boundary-v606-smoke.js'),
    nodeCmd('tools/checks/metadata-store-idempotency-v606-smoke.js'),
    nodeCmd('tools/checks/metadata-cover-access-scope-v606-smoke.js'),
    nodeCmd('tools/checks/csrf-multitab-v605-smoke.js'),
    nodeCmd('tools/checks/csrf-client-retry-v605-smoke.mjs'),
    nodeCmd('tools/checks/fileops-symlink-boundary-v605-smoke.js'),
    nodeCmd('tools/checks/fileops-folder-cache-prescan-v605-smoke.js'),
    nodeCmd('tools/checks/user-state-access-fastpath-v605-smoke.js'),
    nodeCmd('tools/checks/user-state-write-acl-v605-smoke.js'),
    nodeCmd('tools/checks/static-cache-versioning-v605-smoke.js'),
    nodeCmd('tools/checks/shutdown-docker-contract-v605-smoke.js'),
    nodeCmd('tools/checks/account-auth-timing-path-v605-smoke.js'),
    nodeCmd('tools/checks/proxy-scheme-trust-v605-smoke.js'),
    nodeCmd('tools/checks/legacy-sync-disabled-v605-smoke.js'),
    nodeCmd('tools/checks/state-sync-number-validation-v605-smoke.js'),
    nodeCmd('tools/checks/build-mismatch-worker-v605-smoke.js'),
    nodeCmd('tools/checks/docker-library-mount-mode-v605-smoke.js'),
    nodeCmd('tools/checks/json-backup-recovery-v604-smoke.js'),
    nodeCmd('tools/checks/service-backup-recovery-v604-smoke.js'),
    nodeCmd('tools/checks/user-state-api-durability-v604-smoke.js'),
    nodeCmd('tools/checks/metadata-playwright-backup-v604-smoke.js'),
    nodeCmd('tools/checks/auth-asset-revalidation-v604-smoke.js'),
    nodeCmd('tools/checks/metadata-provider-settings-owner-v604-smoke.js'),
    nodeCmd('tools/checks/immutable-icon-versioning-v604-smoke.js'),
    nodeCmd('tools/checks/metadata-provider-profile-privacy-v604-smoke.js'),
    nodeCmd('tools/checks/site-language-backup-only-v604-smoke.js'),
    nodeCmd('tools/checks/recovery-status-async-v604-smoke.js'),
    nodeCmd('tools/checks/build-mismatch-boundary-v604-smoke.js'),
    nodeCmd('tools/checks/session-store-backup-migration-v604-smoke.js'),
    nodeCmd('tools/checks/account-signup-backup-heal-v604-smoke.js'),
    nodeCmd('tools/checks/build-mismatch-client-v604-smoke.js'),
    nodeCmd('tools/checks/service-worker-build-boundary-v604-smoke.js'),
    nodeCmd('tools/checks/user-access-snapshot-payload-v604-smoke.mjs'),
    nodeCmd('tools/checks/service-backup-heal-v604-smoke.js'),
    nodeCmd('tools/checks/metadata-job-isolation-v604-smoke.js'),
    nodeCmd('tools/checks/metadata-job-requester-scale-v604-smoke.js'),
    nodeCmd('tools/checks/metadata-light-context-v604-smoke.js'),
    nodeCmd('tools/checks/json-file-store-durability-v603-smoke.js'),
    nodeCmd('tools/checks/sync-state-durable-flush-v603-smoke.js'),
    nodeCmd('tools/checks/session-store-retry-shutdown-v603-smoke.js'),
    nodeCmd('tools/checks/graceful-shutdown-failure-propagation-v603-smoke.js'),
    nodeCmd('tools/checks/user-state-durable-admin-v603-smoke.js'),
    nodeCmd('tools/checks/user-state-cache-eviction-v603-smoke.js'),
    nodeCmd('tools/checks/content-cache-inflight-invalidation-v603-smoke.js'),
    nodeCmd('tools/checks/disk-cache-janitor-async-v603-smoke.js'),
    nodeCmd('tools/checks/admin-diagnostics-filesystem-async-v603-smoke.js'),
    nodeCmd('tools/checks/metadata-queue-async-durability-v603-smoke.js'),
    nodeCmd('tools/checks/metadata-bulk-async-io-v603-smoke.js'),
    nodeCmd('tools/checks/metadata-cover-async-v603-smoke.js'),
    nodeCmd('tools/checks/account-auth-async-v603-smoke.js'),
    nodeCmd('tools/checks/account-request-scrypt-async-v603-smoke.js'),
    nodeCmd('tools/checks/account-signup-persistence-rollback-v603-smoke.js'),
    nodeCmd('tools/checks/signup-registration-commit-v603-smoke.js'),
    nodeCmd('tools/checks/admin-user-delete-state-rollback-v603-smoke.js'),
    nodeCmd('tools/checks/audit-log-async-security-v603-smoke.js'),
    nodeCmd('tools/checks/security-express-fingerprint-v603-smoke.js'),
    nodeCmd('tools/checks/site-language-async-security-v603-smoke.js'),
    nodeCmd('tools/checks/font-async-atomic-v603-smoke.js'),
    nodeCmd('tools/checks/font-filename-collision-v603-smoke.js'),
    nodeCmd('tools/checks/library-tag-browser-v603-smoke.mjs'),
    nodeCmd('tools/checks/library-tag-window-navigation-v603-smoke.js'),
    nodeCmd('tools/checks/library-user-tag-facet-priority-v603-smoke.js'),
    nodeCmd('tools/checks/initial-load-v600-smoke.js'),
    nodeCmd('tools/checks/client-performance-v600-smoke.js'),
    nodeCmd('tools/checks/library-quick-switcher-v600-smoke.js'),
    nodeCmd('tools/checks/library-user-tags-v600-smoke.js'),
    nodeCmd('tools/checks/library-user-tags-api-v600-smoke.js'),
    nodeCmd('tools/checks/library-tag-facet-v601-smoke.mjs'),
    nodeCmd('tools/checks/library-user-tags-contract-v601-smoke.js'),
    nodeCmd('tools/checks/read-data-user-tags-v601-smoke.mjs'),
    nodeCmd('tools/checks/shared-partial-write-v602-smoke.mjs'),
    nodeCmd('tools/checks/device-state-write-v602-smoke.mjs'),
    nodeCmd('tools/checks/user-state-shelf-cache-v602-smoke.js'),
    nodeCmd('tools/checks/precompressed-negotiation-v602-smoke.js'),
    nodeCmd('tools/checks/service-worker-precache-key-v602-smoke.js'),
    nodeCmd('tools/checks/library-tag-pagination-v602-smoke.js'),
    nodeCmd('tools/checks/library-facet-request-race-v602-smoke.mjs'),
    nodeCmd('tools/checks/library-state-integrity-v602-smoke.js'),
    nodeCmd('tools/checks/metadata-pacing-v600-smoke.js'),
    nodeCmd('tools/checks/mobile-library-v598-smoke.mjs'),
    nodeCmd('tools/checks/mobile-library-structure-v598-smoke.js'),
    nodeCmd('tools/checks/ux-core-v597-smoke.js'),
    nodeCmd('tools/checks/ux-structure-v596-smoke.js'),
    nodeCmd('tools/checks/initial-load-optimization-v595-smoke.js'),
    nodeCmd('tools/checks/ux-core-v594-smoke.js'),
    nodeCmd('tools/checks/metadata-playwright-all-providers-v593-smoke.js'),
    nodeCmd('tools/checks/metadata-playwright-security-persistence-v593-smoke.js'),
    nodeCmd('tools/checks/metadata-permission-button-v593-smoke.js'),
    nodeCmd('tools/checks/page-logout-controls-v593-smoke.js'),
    nodeCmd('tools/checks/audit-log-async-v593-smoke.js'),
    nodeCmd('tools/checks/graceful-shutdown-request-drain-v593-smoke.js'),
    nodeCmd('tools/checks/docs-consolidation-smoke.js'),
    nodeCmd('tools/checks/metadata-store-async-persistence-v592-smoke.js'),
    nodeCmd('tools/checks/metadata-queue-graceful-stop-v592-smoke.js'),
    nodeCmd('tools/checks/fileops-async-serialization-v592-smoke.js'),
    nodeCmd('tools/checks/service-worker-cache-key-v592-smoke.js'),
    nodeCmd('tools/checks/graceful-shutdown-v592-smoke.js'),
    nodeCmd('tools/checks/admin-diagnostics-async-v592-smoke.js'),
    nodeCmd('tools/checks/architecture-storage-contract-v590-smoke.js'),
    nodeCmd('tools/checks/release-output-path-v590-smoke.js'),
    nodeCmd('tools/checks/pwa-service-worker-v590-smoke.js'),
    nodeCmd('tools/checks/metadata-document-access-v590-smoke.js'),
    nodeCmd('tools/checks/smoke-runner-dedupe-v589-smoke.js'),
    nodeCmd('tools/checks/release-verify-default-deps-v589-smoke.js'),
    nodeCmd('tools/checks/version-toast-smoke.js'),
    nodeCmd('tools/checks/theme-shortcut-safe-area-polish-smoke.js'),
    nodeCmd('tools/checks/skeleton-ui-smoke.js'),
    nodeCmd('tools/checks/csp-inline-script-smoke.js'),
    nodeCmd('tools/checks/csp-inline-style-smoke.js'),
    nodeCmd('tools/checks/csp-style-src-hardening-smoke.js'),
    nodeCmd('tools/checks/deployment-guide-smoke.js'),
    nodeCmd('tools/checks/operations-docs-smoke.js'),
    nodeCmd('tools/checks/metadata-docs-smoke.js'),
    nodeCmd('tools/checks/user-login-routing-smoke.js'),
    nodeCmd('tools/checks/user-state-namespace-smoke.js'),
    nodeCmd('tools/checks/multi-user-account-api-smoke.js'),
    nodeCmd('tools/checks/admin-user-management-ui-smoke.js'),
    nodeCmd('tools/checks/folder-mutation-permission-smoke.js'),
    nodeCmd('tools/checks/admin-sectioned-ui-smoke.js'),
    nodeCmd('tools/checks/admin-library-tree-smoke.js'),
    nodeCmd('tools/checks/owner-console-routing-smoke.js'),
    nodeCmd('tools/checks/library-access-folder-prefix-smoke.js'),
    nodeCmd('tools/checks/library-api-acl-smoke.js'),
    nodeCmd('tools/checks/owner-api-boundary-smoke.js'),
    nodeCmd('tools/checks/admin-library-preview-smoke.js'),
    nodeCmd('tools/checks/user-access-snapshot-cache-purge-smoke.js'),
    nodeCmd('tools/checks/font-owner-boundary-smoke.js'),
    nodeCmd('tools/checks/font-user-scope-smoke.js'),
    nodeCmd('tools/checks/multi-user-isolation-boundary-smoke.js'),
    nodeCmd('tools/checks/personal-data-isolation-doc-smoke.js'),
    nodeCmd('tools/checks/font-account-scope-ui-smoke.js'),
    nodeCmd('tools/checks/admin-user-state-management-smoke.js'),
    nodeCmd('tools/checks/admin-user-state-snapshot-smoke.js'),
    nodeCmd('tools/checks/user-state-snapshot-retention-smoke.js'),
    nodeCmd('tools/checks/admin-user-delete-policy-smoke.js'),
    nodeCmd('tools/checks/admin-user-session-revoke-smoke.js'),
    nodeCmd('tools/checks/session-store-lifecycle-v591-smoke.js'),
    nodeCmd('tools/checks/audit-log-service-smoke.js'),
    nodeCmd('tools/checks/audit-log-query-smoke.js'),
    nodeCmd('tools/checks/audit-log-retention-smoke.js'),
    nodeCmd('tools/checks/admin-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-operational-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-preflight-ui-smoke.js'),
    nodeCmd('tools/checks/admin-js-deeper-split-smoke.js'),
    nodeCmd('tools/checks/admin-user-actions-split-smoke.js'),
    nodeCmd('tools/checks/admin-signup-audit-actions-split-smoke.js'),
    nodeCmd('tools/checks/admin-ops-detail-table-smoke.js'),
    nodeCmd('tools/checks/admin-state-actions-split-smoke.js'),
    nodeCmd('tools/checks/admin-permission-actions-split-smoke.js'),
    nodeCmd('tools/checks/admin-diagnostics-filter-smoke.js'),
    nodeCmd('tools/checks/admin-dead-code-after-split-smoke.js'),
    nodeCmd('tools/checks/release-verify-with-server-smoke.js'),
    nodeCmd('tools/checks/recovery-center-compact-ui-smoke.js'),
    nodeCmd('tools/checks/recovery-unused-files-pruned-smoke.js'),
    nodeCmd('tools/checks/recovery-status-actionable-badge-smoke.js'),
    nodeCmd('tools/checks/recovery-reader-stale-cache-summary-smoke.js'),
    nodeCmd('tools/checks/admin-ops-card-details-smoke.js'),
    nodeCmd('tools/checks/admin-ops-diagnostics-readability-smoke.js'),
    nodeCmd('tools/checks/security-hardening-v530-smoke.js'),
    nodeCmd('tools/checks/security-hardening-v531-smoke.js'),
    nodeCmd('tools/checks/security-hardening-v535-smoke.js'),
    nodeCmd('tools/checks/package-lock-regular-file-smoke.js'),
    nodeCmd('tools/checks/package-lock-public-registry-smoke.js'),
    nodeCmd('tools/checks/site-language-pack-bundle-smoke.js'),
    nodeCmd('tools/checks/site-language-bundle-fallback-smoke.js'),
    nodeCmd('tools/checks/site-shared-language-packs-smoke.js'),
    nodeCmd('tools/checks/site-custom-language-settings-smoke.js'),
    nodeCmd('tools/checks/admin-diagnostics-history-smoke.js'),
    nodeCmd('tools/checks/admin-access-preview-compare-smoke.js'),
    nodeCmd('tools/checks/signup-code-register-smoke.js'),
    nodeCmd('tools/checks/signup-code-atomic-smoke.js'),
    nodeCmd('tools/checks/account-password-operations-smoke.js'),
    nodeCmd('tools/checks/search-cache-only-no-network-smoke.js'),
    nodeCmd('tools/checks/search-local-default-no-network-smoke.js'),
    nodeCmd('tools/checks/search-option-dead-code-smoke.js'),
    nodeCmd('tools/checks/search-worker-client-smoke.js'),
    nodeCmd('tools/checks/search-adaptive-listener-cleanup-v591-smoke.js'),
    nodeCmd('tools/checks/search-worker-warm-start-smoke.js'),
    nodeCmd('tools/checks/search-worker-batch-smoke.js'),
    nodeCmd('tools/checks/search-worker-batch-schedule-smoke.js'),
    nodeCmd('tools/checks/search-full-scan-speed-smoke.js'),
    nodeCmd('tools/checks/search-server-load-mitigation-smoke.js'),
    nodeCmd('tools/checks/search-content-cache-limit-smoke.js'),
    nodeCmd('tools/checks/disk-cache-auto-prune-smoke.js'),
    nodeCmd('tools/checks/search-coverage-preview-schedule-smoke.js'),
    nodeCmd('tools/checks/search-modal-close-abort-smoke.js'),
    nodeCmd('tools/checks/search-cache-manifest-smoke.js'),
    nodeCmd('tools/checks/user-access-revoked-current-reader-smoke.js'),
    nodeCmd('tools/checks/account-password-hash-smoke.js'),
    nodeCmd('tools/checks/multi-user-design-doc-smoke.js'),
    nodeCmd('tools/checks/content-cache-rawtext-smoke.js'),
    nodeCmd('tools/checks/precompressed-static-smoke.js'),
    nodeCmd('tools/checks/precompressed-static-metadata-cache-smoke.js'),
    nodeCmd('tools/checks/precompressed-static-async-io-v591-smoke.js'),
    nodeCmd('tools/checks/precompressed-hash-smoke.js'),
    nodeCmd('tools/checks/modulepreload-entrypoints-smoke.js'),
    nodeCmd('tools/checks/lazy-feature-loading-smoke.js'),
    nodeCmd('tools/checks/initial-module-graph-budget-smoke.js'),
    nodeCmd('tools/checks/deferred-ui-fragment-smoke.js'),
    nodeCmd('tools/checks/deferred-ui-runtime-recovery-smoke.mjs'),
    nodeCmd('tools/checks/owner-style-loader-runtime-smoke.mjs'),
    nodeCmd('tools/checks/client-performance-metrics-smoke.js'),
    nodeCmd('tools/checks/library-shelf-dom-budget-smoke.mjs'),
    nodeCmd('tools/checks/content-worker-retry-ux-smoke.mjs'),
    nodeCmd('tools/checks/versioned-rebuild-cache-smoke.js'),
    nodeCmd('tools/checks/block-manifest-conditional-cache-smoke.js'),
    nodeCmd('tools/checks/reader-api-conditional-cache-smoke.js'),
    nodeCmd('tools/checks/reader-api-cache-hardening-smoke.js'),
    nodeCmd('tools/checks/content-cache-io-diagnostics-smoke.js'),
    nodeCmd('tools/checks/content-async-source-io-v591-smoke.js'),
    nodeCmd('tools/checks/block-manifest-async-io-v591-smoke.js'),
    nodeCmd('tools/checks/content-worker-pool-abort-smoke.js'),
    nodeCmd('tools/checks/content-worker-resource-budget-smoke.js'),
    nodeCmd('tools/checks/normalized-content-range-cache-smoke.js'),
    nodeCmd('tools/checks/streaming-normalization-equivalence-smoke.js'),
    nodeCmd('tools/checks/streaming-normalized-content-worker-smoke.js'),
    nodeCmd('tools/checks/normalized-content-cache-recovery-smoke.js'),
    nodeCmd('tools/checks/normalized-content-cache-security-smoke.js'),
    nodeCmd('tools/checks/block-manifest-range-locator-smoke.js'),
    nodeCmd('tools/checks/disk-cache-in-use-protection-smoke.js'),
    nodeCmd('tools/checks/content-large-text-chunk-boundary-smoke.js'),
    nodeCmd('tools/checks/app-shell-force-cache-smoke.js'),
    nodeCmd('tools/checks/periodic-device-sync-dirty-check-smoke.js'),
    nodeCmd('tools/checks/sync-state-lifecycle-v591-smoke.js'),
    nodeCmd('tools/checks/sync-state-data-path-v591-smoke.js'),
    nodeCmd('tools/checks/content-large-file-chunk-cache-smoke.js'),
    nodeCmd('tools/checks/content-large-file-chunk-cache-hardening-smoke.js'),
    nodeCmd('tools/checks/block-manifest-disk-cache-smoke.js'),
    nodeCmd('tools/checks/block-manifest-folder-build-throttle-smoke.js'),
    nodeCmd('tools/checks/block-manifest-window-scope-smoke.js'),
    nodeCmd('tools/checks/block-manifest-episode-disk-cache-smoke.js'),
    nodeCmd('tools/checks/block-manifest-stable-etag-smoke.js'),
    nodeCmd('tools/checks/block-manifest-signature-invalidation-smoke.js'),
    nodeCmd('tools/checks/admin-io-diagnostics-table-smoke.js'),
    nodeCmd('tools/checks/reader-api-cold-warm-cache-smoke.js'),
    nodeCmd('tools/checks/cache-strategy-adjustment-smoke.js'),
    nodeCmd('tools/checks/library-stale-while-revalidate-smoke.js'),
    nodeCmd('tools/checks/docker-entrypoint-wiring-smoke.js'),
    nodeCmd('tools/checks/admin-owner-css-split-review-smoke.js'),
    nodeCmd('tools/checks/css-html-boundary-contract-smoke.js'),
    nodeCmd('tools/checks/modulepreload-cache-policy-boundary-smoke.js'),
    nodeCmd('tools/checks/owner-session-entry-redirect-smoke.js'),
    nodeCmd('tools/checks/owner-session-reader-shell-redirect-smoke.js'),
    nodeCmd('tools/checks/owner-admin-routing-v470-smoke.js'),
    nodeCmd('tools/checks/deployed-cache-header-script-smoke.js'),
    nodeCmd('tools/checks/cache-invalidation-contract-smoke.js'),
    nodeCmd('tools/checks/cache-metrics-threshold-diagnostics-smoke.js'),
    nodeCmd('tools/checks/disk-cache-auto-prune-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-body-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-anchor-trace-export-smoke.js'),
    nodeCmd('tools/checks/reader-anchor-trace-low-overhead-smoke.js'),
    nodeCmd('tools/checks/reader-body-anchor-inertia-retain-smoke.js'),
    nodeCmd('tools/checks/reader-inertia-fixture-expansion-smoke.js'),
    nodeCmd('tools/checks/reader-anchor-regression-report-smoke.js'),
    nodeCmd('tools/checks/reader-safe-area-body-progress-smoke.js'),
    nodeCmd('tools/checks/reader-progress-dataset-guard-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-progress-stability-smoke.js'),
    nodeCmd('tools/checks/reader-buffer-append-current-chunk-retain-smoke.js'),
    nodeCmd('tools/checks/reader-progress-manifest-adoption-guard-smoke.js'),
    nodeCmd('tools/checks/reader-multifile-90-manifest-hold-smoke.js'),
    nodeCmd('tools/checks/reader-unified-append-restore-policy-smoke.js'),
    nodeCmd('tools/checks/reader-append-seam-70-85-progress-fixture-smoke.js'),
    nodeCmd('tools/checks/reader-append-inertia-damp-smoke.js'),
    nodeCmd('tools/checks/reader-ipad-touch-coast-retain-smoke.js'),
    nodeCmd('tools/checks/reader-ipad-touch-native-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-loaded-chunk-append-noop-smoke.js'),
    nodeCmd('tools/checks/reader-coordinate-eviction-smoke.js'),
    nodeCmd('tools/checks/reader-ipad-pseudo-fullscreen-smoke.js'),
    nodeCmd('tools/checks/reader-viewport-transition-anchor-smoke.js'),
    nodeCmd('tools/checks/library-shelf-api-smoke.js'),
    nodeCmd('tools/checks/library-navigation-filter-tree-smoke.mjs'),
    nodeCmd('tools/checks/library-tree-payload-budget-smoke.js'),
    nodeCmd('tools/checks/library-variant-grouping-smoke.js'),
    nodeCmd('tools/checks/library-variant-client-compat-smoke.mjs'),
    nodeCmd('tools/checks/library-variant-api-smoke.js'),
    nodeCmd('tools/checks/library-episode-sequence-grouping-smoke.js'),
    nodeCmd('tools/checks/library-episode-sequence-api-smoke.js'),
    nodeCmd('tools/checks/separate-library-reader-pages-smoke.js'),
    nodeCmd('tools/checks/library-shelf-ui-smoke.js'),
    nodeCmd('tools/checks/library-shelf-shared-state-v585-smoke.mjs'),
    nodeCmd('tools/checks/library-workspace-v581-smoke.js'),
    nodeCmd('tools/checks/library-quick-header-v588-smoke.js'),
    nodeCmd('tools/checks/metadata-access-permission-v588-smoke.js'),
    nodeCmd('tools/checks/metadata-helper-v585-smoke.js'),
    nodeCmd('tools/checks/owner-metadata-settings-v586-smoke.js'),
    nodeCmd('tools/checks/owner-metadata-login-modal-v587-smoke.js'),
    nodeCmd('tools/checks/metadata-playwright-v585-smoke.js'),
    nodeCmd('tools/checks/metadata-pacing-v582-smoke.js'),
    nodeCmd('tools/checks/library-shelf-request-race-smoke.mjs'),
    nodeCmd('tools/checks/library-shelf-resource-budget-smoke.mjs'),
    nodeCmd('tools/checks/library-catalog-performance-smoke.js'),
    nodeCmd('tools/checks/library-async-build-v591-smoke.js'),
    nodeCmd('tools/checks/library-route-async-build-v591-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-row-height-freeze-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-window-hold-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-anchor-restore-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-restore-decision-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-prefetch-window-smoke.js'),
    nodeCmd('tools/checks/novels-api-response-cache-budget-smoke.js'),
    nodeCmd('tools/checks/search-worker-warm-start-smoke.js'),
    nodeCmd('tools/checks/reader-row-measure-cache-diagnostics-smoke.js'),
    nodeCmd('tools/checks/reader-row-measured-margin-height-smoke.js'),
    nodeCmd('tools/checks/reader-actual-bottom-progress-trust-smoke.js'),
    nodeCmd('tools/checks/static-asset-preload-budget-smoke.js'),
    nodeCmd('tools/checks/current-version-lint-smoke.js'),
    nodeCmd('tools/checks/skeleton-timing-polish-smoke.js'),
    nodeCmd('tools/checks/skeleton-empty-state-guard-smoke.js'),
    nodeCmd('tools/checks/release-archive-backup-smoke.js'),
    nodeCmd('tools/checks/settings-connectivity-smoke.js'),
    nodeCmd('tools/checks/settings-account-ui-smoke.js'),
    nodeCmd('tools/checks/multi-file-progress-recent-smoke.js'),
    nodeCmd('tools/checks/library-multifile-disclosure-smoke.js'),
    nodeCmd('tools/checks/library-episode-volume-detection-smoke.js'),
    nodeCmd('tools/checks/pc-sidebar-close-toggle-smoke.js'),
    nodeCmd('tools/checks/site-responsive-sidebar-close-smoke.js'),
    nodeCmd('tools/checks/mobile-modal-layout-smoke.js'),
    nodeCmd('tools/checks/mobile-settings-v585-smoke.js'),
    nodeCmd('tools/check_server_structure.js')
  ]),
  docs: Object.freeze([
    nodeCmd('tools/checks/reader-anchoring-stability-contract-smoke.js'),
    nodeCmd('tools/checks/architecture-storage-contract-v590-smoke.js'),
    nodeCmd('tools/checks/release-output-path-v590-smoke.js'),
    nodeCmd('tools/checks/pwa-service-worker-v590-smoke.js'),
    nodeCmd('tools/checks/metadata-document-access-v590-smoke.js'),
    nodeCmd('tools/checks/smoke-runner-dedupe-v589-smoke.js'),
    nodeCmd('tools/checks/release-verify-default-deps-v589-smoke.js'),
    nodeCmd('tools/checks/docs-consolidation-smoke.js'),
    nodeCmd('tools/checks/deployment-guide-smoke.js'),
    nodeCmd('tools/checks/operations-docs-smoke.js'),
    nodeCmd('tools/checks/metadata-docs-smoke.js'),
    nodeCmd('tools/checks/version-toast-smoke.js')
  ]),
  cache: Object.freeze([
    nodeCmd('tools/checks/metadata-manual-fast-path-v648-smoke.mjs'),
    nodeCmd('tools/checks/metadata-novelpia-cover-v634-smoke.js'),
    nodeCmd('tools/checks/metadata-manual-cover-upload-v634-smoke.js'),
    nodeCmd('tools/checks/metadata-novelpia-adult-playwright-v617-smoke.js'),
    nodeCmd('tools/checks/metadata-novelpia-adult-collection-v617-smoke.js'),
    nodeCmd('tools/checks/recovery-status-async-v604-smoke.js'),
    nodeCmd('tools/checks/json-file-store-durability-v603-smoke.js'),
    nodeCmd('tools/checks/sync-state-durable-flush-v603-smoke.js'),
    nodeCmd('tools/checks/session-store-retry-shutdown-v603-smoke.js'),
    nodeCmd('tools/checks/user-state-durable-admin-v603-smoke.js'),
    nodeCmd('tools/checks/user-state-cache-eviction-v603-smoke.js'),
    nodeCmd('tools/checks/content-cache-inflight-invalidation-v603-smoke.js'),
    nodeCmd('tools/checks/disk-cache-janitor-async-v603-smoke.js'),
    nodeCmd('tools/checks/admin-diagnostics-filesystem-async-v603-smoke.js'),
    nodeCmd('tools/checks/metadata-queue-async-durability-v603-smoke.js'),
    nodeCmd('tools/checks/metadata-bulk-async-io-v603-smoke.js'),
    nodeCmd('tools/checks/metadata-cover-async-v603-smoke.js'),
    nodeCmd('tools/checks/initial-load-optimization-v595-smoke.js'),
    nodeCmd('tools/checks/disk-cache-janitor-lifecycle-v589-smoke.js'),
    nodeCmd('tools/checks/metadata-store-async-persistence-v592-smoke.js'),
    nodeCmd('tools/checks/metadata-queue-graceful-stop-v592-smoke.js'),
    nodeCmd('tools/checks/fileops-async-serialization-v592-smoke.js'),
    nodeCmd('tools/checks/admin-diagnostics-async-v592-smoke.js'),
    nodeCmd('tools/checks/metadata-provider-adapters-smoke.js'),
    nodeCmd('tools/checks/metadata-store-queue-smoke.js'),
    nodeCmd('tools/checks/metadata-queue-persistence-v591-smoke.js'),
    nodeCmd('tools/checks/metadata-queue-persistence-v591-smoke.js'),
    nodeCmd('tools/checks/metadata-cover-cache-smoke.js'),
    nodeCmd('tools/checks/metadata-collection-pipeline-smoke.js'),
    nodeCmd('tools/checks/metadata-bulk-fallback-v578-smoke.js'),
    nodeCmd('tools/checks/metadata-live-recovery-v579-smoke.js'),
    nodeCmd('tools/checks/metadata-pinned-lookup-v580-smoke.js'),
    nodeCmd('tools/checks/user-login-routing-smoke.js'),
    nodeCmd('tools/checks/user-state-namespace-smoke.js'),
    nodeCmd('tools/checks/multi-user-account-api-smoke.js'),
    nodeCmd('tools/checks/admin-user-management-ui-smoke.js'),
    nodeCmd('tools/checks/folder-mutation-permission-smoke.js'),
    nodeCmd('tools/checks/admin-library-tree-smoke.js'),
    nodeCmd('tools/checks/owner-console-routing-smoke.js'),
    nodeCmd('tools/checks/library-access-folder-prefix-smoke.js'),
    nodeCmd('tools/checks/library-api-acl-smoke.js'),
    nodeCmd('tools/checks/owner-api-boundary-smoke.js'),
    nodeCmd('tools/checks/admin-library-preview-smoke.js'),
    nodeCmd('tools/checks/user-access-snapshot-cache-purge-smoke.js'),
    nodeCmd('tools/checks/font-owner-boundary-smoke.js'),
    nodeCmd('tools/checks/font-user-scope-smoke.js'),
    nodeCmd('tools/checks/multi-user-isolation-boundary-smoke.js'),
    nodeCmd('tools/checks/personal-data-isolation-doc-smoke.js'),
    nodeCmd('tools/checks/font-account-scope-ui-smoke.js'),
    nodeCmd('tools/checks/admin-user-state-management-smoke.js'),
    nodeCmd('tools/checks/admin-user-state-snapshot-smoke.js'),
    nodeCmd('tools/checks/user-state-snapshot-retention-smoke.js'),
    nodeCmd('tools/checks/admin-user-delete-policy-smoke.js'),
    nodeCmd('tools/checks/admin-user-session-revoke-smoke.js'),
    nodeCmd('tools/checks/audit-log-service-smoke.js'),
    nodeCmd('tools/checks/audit-log-query-smoke.js'),
    nodeCmd('tools/checks/audit-log-retention-smoke.js'),
    nodeCmd('tools/checks/admin-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-operational-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-preflight-ui-smoke.js'),
    nodeCmd('tools/checks/admin-access-preview-compare-smoke.js'),
    nodeCmd('tools/checks/signup-code-register-smoke.js'),
    nodeCmd('tools/checks/signup-code-atomic-smoke.js'),
    nodeCmd('tools/checks/account-password-operations-smoke.js'),
    nodeCmd('tools/checks/user-access-revoked-current-reader-smoke.js'),
    nodeCmd('tools/checks/account-password-hash-smoke.js'),
    nodeCmd('tools/checks/multi-user-design-doc-smoke.js'),
    nodeCmd('tools/checks/content-cache-rawtext-smoke.js'),
    nodeCmd('tools/checks/search-cache-manifest-smoke.js'),
    nodeCmd('tools/checks/library-deep-signature-cache-smoke.js'),
    nodeCmd('tools/checks/precompressed-static-smoke.js'),
    nodeCmd('tools/checks/precompressed-static-metadata-cache-smoke.js'),
    nodeCmd('tools/checks/precompressed-static-async-io-v591-smoke.js'),
    nodeCmd('tools/checks/modulepreload-entrypoints-smoke.js'),
    nodeCmd('tools/checks/lazy-feature-loading-smoke.js'),
    nodeCmd('tools/checks/initial-module-graph-budget-smoke.js'),
    nodeCmd('tools/checks/deferred-ui-fragment-smoke.js'),
    nodeCmd('tools/checks/deferred-ui-runtime-recovery-smoke.mjs'),
    nodeCmd('tools/checks/owner-style-loader-runtime-smoke.mjs'),
    nodeCmd('tools/checks/client-performance-metrics-smoke.js'),
    nodeCmd('tools/checks/library-shelf-dom-budget-smoke.mjs'),
    nodeCmd('tools/checks/versioned-rebuild-cache-smoke.js'),
    nodeCmd('tools/checks/block-manifest-conditional-cache-smoke.js'),
    nodeCmd('tools/checks/reader-api-conditional-cache-smoke.js'),
    nodeCmd('tools/checks/reader-api-cache-hardening-smoke.js'),
    nodeCmd('tools/checks/content-cache-io-diagnostics-smoke.js'),
    nodeCmd('tools/checks/content-async-source-io-v591-smoke.js'),
    nodeCmd('tools/checks/block-manifest-async-io-v591-smoke.js'),
    nodeCmd('tools/checks/content-worker-pool-abort-smoke.js'),
    nodeCmd('tools/checks/content-worker-resource-budget-smoke.js'),
    nodeCmd('tools/checks/normalized-content-range-cache-smoke.js'),
    nodeCmd('tools/checks/streaming-normalization-equivalence-smoke.js'),
    nodeCmd('tools/checks/streaming-normalized-content-worker-smoke.js'),
    nodeCmd('tools/checks/normalized-content-cache-recovery-smoke.js'),
    nodeCmd('tools/checks/normalized-content-cache-security-smoke.js'),
    nodeCmd('tools/checks/block-manifest-range-locator-smoke.js'),
    nodeCmd('tools/checks/disk-cache-in-use-protection-smoke.js'),
    nodeCmd('tools/checks/content-large-text-chunk-boundary-smoke.js'),
    nodeCmd('tools/checks/app-shell-force-cache-smoke.js'),
    nodeCmd('tools/checks/periodic-device-sync-dirty-check-smoke.js'),
    nodeCmd('tools/checks/sync-state-lifecycle-v591-smoke.js'),
    nodeCmd('tools/checks/sync-state-data-path-v591-smoke.js'),
    nodeCmd('tools/checks/content-large-file-chunk-cache-smoke.js'),
    nodeCmd('tools/checks/content-large-file-chunk-cache-hardening-smoke.js'),
    nodeCmd('tools/checks/block-manifest-disk-cache-smoke.js'),
    nodeCmd('tools/checks/block-manifest-folder-build-throttle-smoke.js'),
    nodeCmd('tools/checks/block-manifest-window-scope-smoke.js'),
    nodeCmd('tools/checks/block-manifest-episode-disk-cache-smoke.js'),
    nodeCmd('tools/checks/block-manifest-stable-etag-smoke.js'),
    nodeCmd('tools/checks/block-manifest-signature-invalidation-smoke.js'),
    nodeCmd('tools/checks/admin-io-diagnostics-table-smoke.js'),
    nodeCmd('tools/checks/reader-api-cold-warm-cache-smoke.js'),
    nodeCmd('tools/checks/cache-strategy-adjustment-smoke.js'),
    nodeCmd('tools/checks/library-stale-while-revalidate-smoke.js'),
    nodeCmd('tools/checks/docker-entrypoint-wiring-smoke.js'),
    nodeCmd('tools/checks/admin-owner-css-split-review-smoke.js'),
    nodeCmd('tools/checks/css-html-boundary-contract-smoke.js'),
    nodeCmd('tools/checks/modulepreload-cache-policy-boundary-smoke.js'),
    nodeCmd('tools/checks/owner-session-entry-redirect-smoke.js'),
    nodeCmd('tools/checks/owner-session-reader-shell-redirect-smoke.js'),
    nodeCmd('tools/checks/owner-admin-routing-v470-smoke.js'),
    nodeCmd('tools/checks/deployed-cache-header-script-smoke.js'),
    nodeCmd('tools/checks/cache-invalidation-contract-smoke.js'),
    nodeCmd('tools/checks/cache-metrics-threshold-diagnostics-smoke.js'),
    nodeCmd('tools/checks/disk-cache-auto-prune-smoke.js'),
    nodeCmd('tools/checks/library-catalog-performance-smoke.js'),
    nodeCmd('tools/checks/library-async-build-v591-smoke.js'),
    nodeCmd('tools/checks/library-route-async-build-v591-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-row-height-freeze-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-window-hold-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-anchor-restore-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-restore-decision-smoke.js'),
    nodeCmd('tools/checks/library-virtual-scroll-prefetch-window-smoke.js'),
    nodeCmd('tools/checks/novels-api-response-cache-budget-smoke.js'),
    nodeCmd('tools/checks/static-asset-preload-budget-smoke.js')
  ]),
  security: Object.freeze([
    nodeCmd('tools/checks/v663-assets-csp-cover-smoke.mjs'),
    nodeCmd('tools/checks/security-reaudit-v625-smoke.js'),
    nodeCmd('tools/checks/metadata-playwright-secure-fast-v625-smoke.js'),
    nodeCmd('tools/checks/session-logout-durability-v606-smoke.js'),
    nodeCmd('tools/checks/login-session-durability-v606-smoke.js'),
    nodeCmd('tools/checks/precompressed-http-boundary-v606-smoke.js'),
    nodeCmd('tools/checks/metadata-cover-access-scope-v606-smoke.js'),
    nodeCmd('tools/checks/csrf-multitab-v605-smoke.js'),
    nodeCmd('tools/checks/csrf-client-retry-v605-smoke.mjs'),
    nodeCmd('tools/checks/fileops-symlink-boundary-v605-smoke.js'),
    nodeCmd('tools/checks/static-cache-versioning-v605-smoke.js'),
    nodeCmd('tools/checks/account-auth-timing-path-v605-smoke.js'),
    nodeCmd('tools/checks/proxy-scheme-trust-v605-smoke.js'),
    nodeCmd('tools/checks/legacy-sync-disabled-v605-smoke.js'),
    nodeCmd('tools/checks/state-sync-number-validation-v605-smoke.js'),
    nodeCmd('tools/checks/build-mismatch-worker-v605-smoke.js'),
    nodeCmd('tools/checks/metadata-provider-profile-privacy-v604-smoke.js'),
    nodeCmd('tools/checks/site-language-backup-only-v604-smoke.js'),
    nodeCmd('tools/checks/build-mismatch-boundary-v604-smoke.js'),
    nodeCmd('tools/checks/immutable-icon-versioning-v604-smoke.js'),
    nodeCmd('tools/checks/session-store-backup-migration-v604-smoke.js'),
    nodeCmd('tools/checks/account-signup-backup-heal-v604-smoke.js'),
    nodeCmd('tools/checks/build-mismatch-client-v604-smoke.js'),
    nodeCmd('tools/checks/service-worker-build-boundary-v604-smoke.js'),
    nodeCmd('tools/checks/user-access-snapshot-payload-v604-smoke.mjs'),
    nodeCmd('tools/checks/service-backup-heal-v604-smoke.js'),
    nodeCmd('tools/checks/metadata-job-isolation-v604-smoke.js'),
    nodeCmd('tools/checks/metadata-job-requester-scale-v604-smoke.js'),
    nodeCmd('tools/checks/metadata-light-context-v604-smoke.js'),
    nodeCmd('tools/checks/account-auth-async-v603-smoke.js'),
    nodeCmd('tools/checks/account-request-scrypt-async-v603-smoke.js'),
    nodeCmd('tools/checks/account-signup-persistence-rollback-v603-smoke.js'),
    nodeCmd('tools/checks/signup-registration-commit-v603-smoke.js'),
    nodeCmd('tools/checks/admin-user-delete-state-rollback-v603-smoke.js'),
    nodeCmd('tools/checks/audit-log-async-security-v603-smoke.js'),
    nodeCmd('tools/checks/security-express-fingerprint-v603-smoke.js'),
    nodeCmd('tools/checks/site-language-async-security-v603-smoke.js'),
    nodeCmd('tools/checks/session-store-retry-shutdown-v603-smoke.js'),
    nodeCmd('tools/checks/graceful-shutdown-failure-propagation-v603-smoke.js'),
    nodeCmd('tools/checks/font-async-atomic-v603-smoke.js'),
    nodeCmd('tools/checks/font-filename-collision-v603-smoke.js'),
    nodeCmd('tools/checks/ux-structure-v596-smoke.js'),
    nodeCmd('tools/checks/ux-core-v594-smoke.js'),
    nodeCmd('tools/checks/metadata-playwright-all-providers-v593-smoke.js'),
    nodeCmd('tools/checks/metadata-playwright-security-persistence-v593-smoke.js'),
    nodeCmd('tools/checks/metadata-permission-button-v593-smoke.js'),
    nodeCmd('tools/checks/page-logout-controls-v593-smoke.js'),
    nodeCmd('tools/checks/audit-log-async-v593-smoke.js'),
    nodeCmd('tools/checks/graceful-shutdown-request-drain-v593-smoke.js'),
    nodeCmd('tools/checks/pwa-service-worker-v590-smoke.js'),
    nodeCmd('tools/checks/service-worker-cache-key-v592-smoke.js'),
    nodeCmd('tools/checks/graceful-shutdown-v592-smoke.js'),
    nodeCmd('tools/checks/fileops-async-serialization-v592-smoke.js'),
    nodeCmd('tools/checks/metadata-document-access-v590-smoke.js'),
    nodeCmd('tools/checks/full-audit-fixes-v622-smoke.js'),
    nodeCmd('tools/checks/metadata-transport-security-smoke.js'),
    nodeCmd('tools/checks/metadata-pinned-lookup-v580-smoke.js'),
    nodeCmd('tools/checks/metadata-routes-access-smoke.js'),
    nodeCmd('tools/checks/metadata-access-permission-v588-smoke.js'),
    nodeCmd('tools/checks/session-store-lifecycle-v591-smoke.js'),
    nodeCmd('tools/checks/session-cookie-host-prefix-smoke.js'),
    nodeCmd('tools/checks/production-password-policy-smoke.js'),
    nodeCmd('tools/checks/custom-css-security-smoke.js'),
    nodeCmd('tools/checks/state-record-key-v601-smoke.js'),
    nodeCmd('tools/checks/read-data-record-key-v601-smoke.mjs'),
    nodeCmd('tools/checks/shared-partial-write-v602-smoke.mjs'),
    nodeCmd('tools/checks/device-state-write-v602-smoke.mjs'),
    nodeCmd('tools/checks/user-state-shelf-cache-v602-smoke.js'),
    nodeCmd('tools/checks/precompressed-negotiation-v602-smoke.js'),
    nodeCmd('tools/checks/service-worker-precache-key-v602-smoke.js'),
    nodeCmd('tools/checks/security-headers-smoke.js'),
    nodeCmd('tools/checks/csp-inline-script-smoke.js'),
    nodeCmd('tools/checks/csp-inline-style-smoke.js'),
    nodeCmd('tools/checks/csp-style-src-hardening-smoke.js'),
    nodeCmd('tools/checks/public-asset-allowlist-smoke.js'),
    nodeCmd('tools/checks/strict-origin-fetch-metadata-smoke.js'),
    nodeCmd('tools/checks/fileops-confirmation-smoke.js'),
    nodeCmd('tools/checks/rate-limit-prune-smoke.js'),
    nodeCmd('tools/checks/login-origin-healthz-smoke.js'),
    nodeCmd('tools/checks/login-session-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-cloudflare-visitor-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-cloudflare-tunnel-exposure-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-ops-diagnostics-readability-smoke.js'),
    nodeCmd('tools/checks/security-hardening-v530-smoke.js'),
    nodeCmd('tools/checks/security-hardening-v531-smoke.js'),
    nodeCmd('tools/checks/security-hardening-v535-smoke.js'),
    nodeCmd('tools/checks/font-owner-boundary-smoke.js'),
    nodeCmd('tools/checks/font-user-scope-smoke.js'),
    nodeCmd('tools/checks/multi-user-isolation-boundary-smoke.js'),
    nodeCmd('tools/checks/personal-data-isolation-doc-smoke.js'),
    nodeCmd('tools/checks/font-account-scope-ui-smoke.js'),
    nodeCmd('tools/checks/admin-user-session-revoke-smoke.js'),
    nodeCmd('tools/checks/audit-log-service-smoke.js'),
    nodeCmd('tools/checks/audit-log-query-smoke.js'),
    nodeCmd('tools/checks/audit-log-retention-smoke.js'),
    nodeCmd('tools/checks/admin-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-operational-diagnostics-smoke.js'),
    nodeCmd('tools/checks/admin-preflight-ui-smoke.js'),
    nodeCmd('tools/checks/admin-access-preview-compare-smoke.js'),
    nodeCmd('tools/checks/signup-code-register-smoke.js'),
    nodeCmd('tools/checks/signup-code-atomic-smoke.js'),
    nodeCmd('tools/checks/account-password-operations-smoke.js'),
    nodeCmd('tools/checks/admin-user-state-snapshot-smoke.js'),
    nodeCmd('tools/checks/library-readonly-mutation-error-smoke.js'),
    nodeCmd('tools/checks/folder-mutation-permission-smoke.js')
  ]),
  reader: Object.freeze([
    nodeCmd('tools/checks/reader-search-modal-v647-smoke.js'),
    nodeCmd('tools/checks/library-reader-ui-v645-smoke.js'),
    nodeCmd('tools/checks/network-search-mode-v645-smoke.js'),
    nodeCmd('tools/checks/deferred-ui-style-recovery-v645-smoke.js'),
    nodeCmd('tools/checks/content-worker-retry-ux-smoke.mjs'),
    nodeCmd('tools/checks/block-manifest-range-locator-smoke.js'),
    nodeCmd('tools/checks/reader-native-large-correction-guard-smoke.js'),
    nodeCmd('tools/checks/reader-virtual-layout-cache-smoke.js'),
    nodeCmd('tools/checks/reader-anchoring-stability-contract-smoke.js'),
    nodeCmd('tools/checks/reader-append-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-multi-episode-append-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-scroll-buffer-patch-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-append-deferred-spacer-sync-smoke.js'),
    nodeCmd('tools/checks/reader-append-seam-render-smoke.js'),
    nodeCmd('tools/checks/reader-append-seam-anchor-correction-smoke.js'),
    nodeCmd('tools/checks/reader-append-seam-native-scroll-retain-smoke.js'),
    nodeCmd('tools/checks/reader-native-forward-scroll-retain-smoke.js'),
    nodeCmd('tools/checks/reader-native-forward-seam-transit-lock-smoke.js'),
    nodeCmd('tools/checks/reader-native-forward-seam-render-hold-smoke.js'),
    nodeCmd('tools/checks/reader-append-upward-correction-guard-smoke.js'),
    nodeCmd('tools/checks/reader-append-native-upward-retain-smoke.js'),
    nodeCmd('tools/checks/reader-append-correction-guard-smoke.js'),
    nodeCmd('tools/checks/reader-prune-exact-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-prune-prefix-delta-guard-smoke.js'),
    nodeCmd('tools/checks/reader-native-scroll-retain-smoke.js'),
    nodeCmd('tools/checks/reader-trusted-bottom-progress-smoke.js'),
    nodeCmd('tools/checks/reader-small-episode-chunk-boundary-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-body-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-anchor-trace-export-smoke.js'),
    nodeCmd('tools/checks/reader-anchor-trace-low-overhead-smoke.js'),
    nodeCmd('tools/checks/reader-body-anchor-inertia-retain-smoke.js'),
    nodeCmd('tools/checks/reader-inertia-fixture-expansion-smoke.js'),
    nodeCmd('tools/checks/reader-anchor-regression-report-smoke.js'),
    nodeCmd('tools/checks/reader-safe-area-body-progress-smoke.js'),
    nodeCmd('tools/checks/reader-progress-dataset-guard-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-progress-stability-smoke.js'),
    nodeCmd('tools/checks/reader-buffer-append-current-chunk-retain-smoke.js'),
    nodeCmd('tools/checks/reader-progress-manifest-adoption-guard-smoke.js'),
    nodeCmd('tools/checks/reader-multifile-90-manifest-hold-smoke.js'),
    nodeCmd('tools/checks/reader-unified-append-restore-policy-smoke.js'),
    nodeCmd('tools/checks/reader-append-seam-70-85-progress-fixture-smoke.js'),
    nodeCmd('tools/checks/reader-append-inertia-damp-smoke.js'),
    nodeCmd('tools/checks/reader-ipad-touch-coast-retain-smoke.js'),
    nodeCmd('tools/checks/reader-ipad-touch-native-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-loaded-chunk-append-noop-smoke.js'),
    nodeCmd('tools/checks/reader-ipad-pseudo-fullscreen-smoke.js'),
    nodeCmd('tools/checks/reader-viewport-transition-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-multifile-native-scroll-anchor-stabilization-smoke.js'),
    nodeCmd('tools/checks/reader-multifile-native-settle-exact-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-scroll-settle-exact-anchor-restore-smoke.js'),
    nodeCmd('tools/checks/reader-append-incremental-delta-layout-smoke.js'),
    nodeCmd('tools/checks/reader-row-measure-cache-diagnostics-smoke.js'),
    nodeCmd('tools/checks/reader-row-measured-margin-height-smoke.js'),
    nodeCmd('tools/checks/reader-actual-bottom-progress-trust-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-local-slider-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-slider-totalchunks-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-slider-dom-progress-smoke.js'),
    nodeCmd('tools/checks/reader-safe-area-multifile-progress-smoke.js'),
    nodeCmd('tools/checks/reader-multifile-resume-local-ratio-smoke.js'),
    nodeCmd('tools/checks/reader-coordinate-policy-v470-smoke.js'),
    nodeCmd('tools/checks/reader-prev-boundary-top-indicator-smoke.js'),
    nodeCmd('tools/checks/reader-slider-char-target-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-full-file-char-progress-direct-smoke.js'),
    nodeCmd('tools/checks/reader-coordinate-eviction-smoke.js'),
    nodeCmd('tools/checks/pill-status-samsung-pwa-inline-lock-removed-smoke.js'),
    nodeCmd('tools/checks/status-pill-fullscreen-compact-smoke.js'),
    nodeCmd('tools/checks/fullscreen-pill-safe-area-style-smoke.js'),
    nodeCmd('tools/checks/reader-bottom-ratio-boundary-lock-smoke.js'),
    nodeCmd('tools/checks/reader-episode-bottom-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-episode-boundary-mode-smoke.js'),
    nodeCmd('tools/checks/reader-jump-panel-episode-select-smoke.js'),
    nodeCmd('tools/checks/reader-native-scroll-settle-freeze-smoke.js'),
    nodeCmd('tools/checks/reader-nav-terminal-progress-sync-smoke.js'),
    nodeCmd('tools/checks/reader-nav-slider-release-commit-smoke.js'),
    nodeCmd('tools/checks/reader-nav-slider-anchor-offset-smoke.js'),
    nodeCmd('tools/checks/reader-nav-slider-in-window-jump-smoke.js'),
    nodeCmd('tools/checks/multi-file-progress-recent-smoke.js'),

    nodeCmd('tools/checks/reader-context-progress-flush-v607-smoke.js'),
    nodeCmd('tools/checks/reader-open-session-guard-v607-smoke.js'),
    nodeCmd('tools/checks/reader-loading-owner-v607-smoke.js'),
    nodeCmd('tools/checks/reader-lifecycle-timer-offline-v607-smoke.js'),
    nodeCmd('tools/checks/reader-race-ownership-v608-smoke.mjs'),
  ]),

  search: Object.freeze([
    nodeCmd('tools/checks/reader-search-modal-v647-smoke.js'),
    nodeCmd('tools/checks/network-search-mode-v645-smoke.js'),
    nodeCmd('tools/checks/deferred-ui-style-recovery-v645-smoke.js'),
    nodeCmd('tools/checks/search-multi-episode-full-scan-smoke.js'),
    nodeCmd('tools/checks/search-v364-runtime-smoke.js'),
    nodeCmd('tools/checks/search-continue-during-navigation-smoke.js'),
    nodeCmd('tools/checks/search-compact-status-smoke.js'),
    nodeCmd('tools/checks/search-cache-only-no-network-smoke.js'),
    nodeCmd('tools/checks/search-local-default-no-network-smoke.js'),
    nodeCmd('tools/checks/search-worker-client-smoke.js'),
    nodeCmd('tools/checks/search-adaptive-listener-cleanup-v591-smoke.js'),
    nodeCmd('tools/checks/search-worker-warm-start-smoke.js'),
    nodeCmd('tools/checks/search-worker-batch-smoke.js'),
    nodeCmd('tools/checks/search-worker-batch-schedule-smoke.js'),
    nodeCmd('tools/checks/search-full-scan-speed-smoke.js'),
    nodeCmd('tools/checks/search-server-load-mitigation-smoke.js'),
    nodeCmd('tools/checks/search-content-cache-limit-smoke.js'),
    nodeCmd('tools/checks/search-coverage-preview-schedule-smoke.js'),
    nodeCmd('tools/checks/search-modal-close-abort-smoke.js'),
    nodeCmd('tools/checks/search-cache-manifest-smoke.js')
  ]),
  settings: Object.freeze([
    nodeCmd('tools/checks/library-settings-diagnostics-v647-smoke.mjs'),
    nodeCmd('tools/checks/site-language-backup-only-v604-smoke.js'),
    nodeCmd('tools/checks/font-async-atomic-v603-smoke.js'),
    nodeCmd('tools/checks/font-filename-collision-v603-smoke.js'),
    nodeCmd('tools/checks/site-language-async-security-v603-smoke.js'),
    nodeCmd('tools/checks/library-tag-browser-v603-smoke.mjs'),
    nodeCmd('tools/checks/library-tag-window-navigation-v603-smoke.js'),
    nodeCmd('tools/checks/library-user-tag-facet-priority-v603-smoke.js'),
    nodeCmd('tools/checks/settings-information-architecture-smoke.js'),
    nodeCmd('tools/checks/settings-connectivity-smoke.js'),
    nodeCmd('tools/checks/settings-account-ui-smoke.js'),
    nodeCmd('tools/checks/site-language-bundle-fallback-smoke.js'),
    nodeCmd('tools/checks/site-custom-language-settings-smoke.js'),
    nodeCmd('tools/checks/settings-functional-controls-smoke.js'),
    nodeCmd('tools/checks/settings-reader-preset-buttons-smoke.js'),
    nodeCmd('tools/checks/pc-sidebar-close-toggle-smoke.js'),
    nodeCmd('tools/checks/site-responsive-sidebar-close-smoke.js'),
    nodeCmd('tools/checks/mobile-modal-layout-smoke.js'),
    nodeCmd('tools/checks/mobile-settings-v585-smoke.js'),
    nodeCmd('tools/checks/theme-shortcut-safe-area-polish-smoke.js'),
    nodeCmd('tools/checks/settings-nested-modal-stack-v577-smoke.js')
  ]),
  frontend: Object.freeze([
    nodeCmd('tools/checks/v666-non-auth-autofill-guard-smoke.js'),
    nodeCmd('tools/checks/metadata-library-ui-smoke.mjs'),
    nodeCmd('tools/checks/library-page-view-mode-v577-smoke.js'),
    nodeCmd('tools/checks/library-tree-redesign-v577-smoke.js'),
    nodeCmd('tools/checks/metadata-dedicated-page-v577-smoke.js'),
    nodeCmd('tools/checks/metadata-theme-bulk-v578-smoke.js'),
    nodeCmd('tools/check_rebuild_frontend.js', '--quiet-ok'),
    nodeCmd('tools/check_frontend_supervisor.js', '--quiet-ok')
  ]),
  server: Object.freeze([
    nodeCmd('tools/checks/metadata-shelf-enrichment-smoke.js'),
    nodeCmd('tools/check_server_structure.js'),
    nodeCmd('tools/smoke_server_http.js')
  ]),
  audit: Object.freeze([
    nodeCmd('tools/checks/release-verify-current-coverage-v682-smoke.js'),
    nodeCmd('tools/checks/v682-active-check-registration-smoke.js'),
    nodeCmd('tools/checks/v682-library-organization-powershell51-compat-smoke.js'),
    nodeCmd('tools/checks/v681-metadata-manual-provider-filter-smoke.js'),
    nodeCmd('tools/checks/release-verify-current-coverage-v680-smoke.js'),
    nodeCmd('tools/checks/v680-active-check-registration-smoke.js'),
    nodeCmd('tools/checks/v680-login-owner-palette-smoke.js'),
    nodeCmd('tools/checks/v680-user-theme-bootstrap-smoke.js'),
    nodeCmd('tools/checks/v680-theme-runtime-contract-smoke.js'),
    nodeCmd('tools/checks/v678-extension-popup-fixed-width-smoke.js'),
    nodeCmd('tools/checks/v678-extension-popup-narrow-layout-smoke.js'),
    nodeCmd('tools/checks/v678-metadata-folder-theme-smoke.js'),
    nodeCmd('tools/checks/v679-metadata-folder-disclosure-smoke.js'),
    nodeCmd('tools/checks/v677-metadata-hard-cap-incremental-smoke.js'),
    nodeCmd('tools/checks/v677-library-tree-folder-cursor-smoke.js'),
    nodeCmd('tools/checks/v677-cover-audit-nofollow-smoke.js'),
    nodeCmd('tools/checks/v677-package-format-parser-smoke.js'),
    nodeCmd('tools/checks/v677-runtime-dependency-install-smoke.js'),
    nodeCmd('tools/checks/v676-compose-environment-yaml-smoke.js'),
    nodeCmd('tools/checks/v676-trusted-proxy-validation-smoke.js'),
    nodeCmd('tools/checks/v676-metadata-bounded-resident-smoke.js'),
    nodeCmd('tools/checks/v676-reader-prefetch-orphan-circuit-smoke.mjs'),
    nodeCmd('tools/checks/v676-modal-stack-runtime-smoke.mjs'),
    nodeCmd('tools/checks/v676-font-io-error-propagation-smoke.js'),
    nodeCmd('tools/checks/v676-progress-journal-symlink-smoke.js'),
    nodeCmd('tools/checks/v676-extension-shortcut-responsive-smoke.js'),
    nodeCmd('tools/checks/v676-metadata-folder-continuity-smoke.mjs'),
    nodeCmd('tools/checks/v675-progress-delta-journal-smoke.js'),
    nodeCmd('tools/checks/v675-metadata-compact-index-smoke.js'),
    nodeCmd('tools/checks/v675-trusted-proxy-source-smoke.js'),
    nodeCmd('tools/checks/v675-reader-prefetch-watchdog-smoke.mjs'),
    nodeCmd('tools/checks/v675-service-worker-dual-failure-smoke.js'),
    nodeCmd('tools/checks/v675-font-symlink-boundary-smoke.js'),
    nodeCmd('tools/checks/v675-modal-focus-manager-smoke.mjs'),
    nodeCmd('tools/checks/v675-profile-skeleton-smoke.mjs'),
    nodeCmd('tools/checks/v674-progress-local-compaction-smoke.mjs'),
    nodeCmd('tools/checks/v674-reader-prefetch-cancel-race-smoke.mjs'),
    nodeCmd('tools/checks/v674-library-bounded-fallback-smoke.mjs'),
    nodeCmd('tools/checks/v674-service-worker-navigation-state-failure-smoke.js'),
    nodeCmd('tools/checks/v674-server-filesystem-durability-smoke.js'),
    nodeCmd('tools/checks/v674-server-device-profile-cap-smoke.js'),
    nodeCmd('tools/checks/v674-metadata-playwright-dns-pinning-smoke.js'),
    nodeCmd('tools/checks/v674-cross-platform-gate-contract-smoke.js'),
    nodeCmd('tools/checks/v673-metadata-applied-index-smoke.js'),
    nodeCmd('tools/checks/v673-metadata-applied-shard-smoke.js'),
    nodeCmd('tools/checks/v673-metadata-candidate-shard-race-smoke.js'),
    nodeCmd('tools/checks/v673-metadata-sparse-shard-init-smoke.js'),
    nodeCmd('tools/checks/v673-library-shelf-hot-path-smoke.js'),
    nodeCmd('tools/checks/v673-library-variant-coarse-bucket-smoke.js'),
    nodeCmd('tools/checks/v673-disk-cache-bounded-candidate-smoke.js'),
    nodeCmd('tools/checks/library-durable-invalidation-v648-smoke.js'),
    nodeCmd('tools/checks/library-request-boundary-v648-smoke.js'),
    nodeCmd('tools/checks/v648-audit-runtime-fixes-smoke.mjs'),
    nodeCmd('tools/checks/metadata-ssn-live-contract-v641.js'),
    nodeCmd('tools/checks/api-boundary-v611-smoke.js'),
    nodeCmd('tools/checks/progress-delta-v612-smoke.mjs'),
    nodeCmd('tools/checks/progress-storage-coalesce-v612-smoke.mjs'),
    nodeCmd('tools/checks/library-async-event-guard-v612-smoke.mjs'),
    nodeCmd('tools/checks/library-access-snapshot-v612-smoke.mjs'),
    nodeCmd('tools/checks/archive-safety-v611-smoke.js'),
    nodeCmd('tools/checks/deployment-probe-v611-smoke.js'),
    nodeCmd('tools/checks/package-archive-fallback-v610-smoke.js'),
    nodeCmd('tools/checks/async-route-v610-smoke.js'),
    nodeCmd('tools/checks/shutdown-contract-v610-smoke.js'),
    nodeCmd('tools/checks/deployment-state-boot-v610-smoke.js'),
    nodeCmd('tools/checks/font-sync-atomic-v610-smoke.js'),
    nodeCmd('tools/checks/smoke-runner-orphan-coverage-v609-smoke.js'),
    nodeCmd('tools/checks/esm-unused-named-import-v609-smoke.js'),
    nodeCmd('tools/checks/cjs-unused-destructured-require-v609-smoke.js'),
    nodeCmd('tools/checks/release-verify-lockfile-fallback-v609-smoke.js'),
    nodeCmd('tools/checks/block-manifest-block-char-ranges-smoke.js'),
    nodeCmd('tools/checks/deployment-mode-proxy-smoke.js'),
    nodeCmd('tools/checks/initial-load-browser-v599-smoke.js'),
    nodeCmd('tools/checks/initial-load-v599-smoke.js'),
    nodeCmd('tools/checks/library-filename-search-smoke.js'),
    nodeCmd('tools/checks/metadata-auth-ui-v585-smoke.js'),
    nodeCmd('tools/checks/metadata-helper-v584-smoke.js'),
    nodeCmd('tools/checks/metadata-playwright-v584-smoke.js'),
    nodeCmd('tools/checks/mobile-library-browser-v598-smoke.js'),
    nodeCmd('tools/checks/pill-status-fullscreen-strict-smoke.js'),
    nodeCmd('tools/checks/pill-toast-fullscreen-height-smoke.js'),
    nodeCmd('tools/checks/reader-append-file-char-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-append-seam-progress-diagnostic-smoke.js'),
    nodeCmd('tools/checks/reader-append-seam-scrolltop-diagnostic-smoke.js'),
    nodeCmd('tools/checks/reader-boundary-pull-v471-smoke.js'),
    nodeCmd('tools/checks/reader-contained-visible-row-progress-smoke.js'),
    nodeCmd('tools/checks/reader-debug-snapshot-progress-smoke.js'),
    nodeCmd('tools/checks/reader-episode-bottom-anchor-strict-gate-smoke.js'),
    nodeCmd('tools/checks/reader-file-char-viewport-progress-smoke.js'),
    nodeCmd('tools/checks/reader-full-file-char-progress-smoke.js'),
    nodeCmd('tools/checks/reader-full-file-visible-row-measured-progress-smoke.js'),
    nodeCmd('tools/checks/reader-live-scroll-progress-smoke.js'),
    nodeCmd('tools/checks/reader-manifest-block-fallback-progress-smoke.js'),
    nodeCmd('tools/checks/reader-mobile-7080-anchor-hold-smoke.js'),
    nodeCmd('tools/checks/reader-multi-file-slider-manifest-smoke.js'),
    nodeCmd('tools/checks/reader-native-backward-measure-freeze-smoke.js'),
    nodeCmd('tools/checks/reader-native-forward-measure-freeze-smoke.js'),
    nodeCmd('tools/checks/reader-prepend-file-char-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-prepend-seam-scrolltop-diagnostic-smoke.js'),
    nodeCmd('tools/checks/reader-programmatic-scroll-isolation-smoke.js'),
    nodeCmd('tools/checks/reader-progress-coordinate-scope-fix-smoke.js'),
    nodeCmd('tools/checks/reader-single-file-guard-scope-smoke.js'),
    nodeCmd('tools/checks/reader-slider-block-direct-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-slider-coast-thumb-settle-smoke.js'),
    nodeCmd('tools/checks/reader-slider-file-char-progress-smoke.js'),
    nodeCmd('tools/checks/reader-slider-measured-char-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-slider-programmatic-scroll-isolation-smoke.js'),
    nodeCmd('tools/checks/reader-slider-ratio-anchor-smoke.js'),
    nodeCmd('tools/checks/reader-slider-stale-measure-target-clear-smoke.js'),
    nodeCmd('tools/checks/reader-stability-protection-runner-smoke.js'),
    nodeCmd('tools/checks/reader-top-prev-boundary-pull-smoke.js'),
    nodeCmd('tools/checks/recovery-library-diagnostics-lightweight-smoke.js'),
    nodeCmd('tools/checks/safe-area-css-ownership-budget-smoke.js'),
    nodeCmd('tools/checks/safe-area-iterative-collision-fit-smoke.js'),
    nodeCmd('tools/checks/safe-area-strict-collision-trim-smoke.js'),
    nodeCmd('tools/checks/safe-remaining-stable-estimate-smoke.js'),
    nodeCmd('tools/checks/search-remote-pill-compaction-smoke.js'),
    nodeCmd('tools/checks/server-text-encoding-autodetect-smoke.js'),
    nodeCmd('tools/checks/signup-code-full-search-permission-smoke.js'),
    nodeCmd('tools/checks/status-pill-bars-visibility-role-smoke.js'),
    nodeCmd('tools/checks/ux-browser-v596-smoke.js'),
    nodeCmd('tools/checks/ux-browser-v597-smoke.js')
  ])
});

const COMPOSITE_GROUPS = Object.freeze({
  standard: Object.freeze([
    nodeCmd('tools/checks/initial-load-v600-smoke.js'),
    nodeCmd('tools/checks/client-performance-v600-smoke.js'),
    nodeCmd('tools/checks/library-quick-switcher-v600-smoke.js'),
    nodeCmd('tools/checks/library-user-tags-v600-smoke.js'),
    nodeCmd('tools/checks/library-user-tags-api-v600-smoke.js'),
    nodeCmd('tools/checks/library-tag-facet-v601-smoke.mjs'),
    nodeCmd('tools/checks/library-user-tags-contract-v601-smoke.js'),
    nodeCmd('tools/checks/read-data-user-tags-v601-smoke.mjs'),
    nodeCmd('tools/checks/shared-partial-write-v602-smoke.mjs'),
    nodeCmd('tools/checks/device-state-write-v602-smoke.mjs'),
    nodeCmd('tools/checks/user-state-shelf-cache-v602-smoke.js'),
    nodeCmd('tools/checks/precompressed-negotiation-v602-smoke.js'),
    nodeCmd('tools/checks/service-worker-precache-key-v602-smoke.js'),
    nodeCmd('tools/checks/library-tag-pagination-v602-smoke.js'),
    nodeCmd('tools/checks/library-facet-request-race-v602-smoke.mjs'),
    nodeCmd('tools/checks/library-state-integrity-v602-smoke.js'),
    nodeCmd('tools/checks/metadata-pacing-v600-smoke.js'),
    nodeCmd('tools/checks/mobile-library-v598-smoke.mjs'),
    nodeCmd('tools/checks/mobile-library-structure-v598-smoke.js'),
    nodeCmd('tools/checks/ux-core-v597-smoke.js'),
    ...GROUPS.docs,
    ...GROUPS.cache,
    ...GROUPS.security,
    ...GROUPS.reader,
    ...GROUPS.search,
    ...GROUPS.settings,
    nodeCmd('tools/checks/library-multifile-disclosure-smoke.js'),
    nodeCmd('tools/checks/library-episode-volume-detection-smoke.js'),
    nodeCmd('tools/checks/pc-sidebar-close-toggle-smoke.js'),
    nodeCmd('tools/checks/site-responsive-sidebar-close-smoke.js'),
    nodeCmd('tools/checks/mobile-modal-layout-smoke.js'),
    nodeCmd('tools/checks/mobile-settings-v585-smoke.js'),
    nodeCmd('tools/check_server_structure.js'),
    nodeCmd('tools/smoke_server_http.js')
  ]),
  full: Object.freeze([
    nodeCmd('tools/checks/initial-load-v600-smoke.js'),
    nodeCmd('tools/checks/client-performance-v600-smoke.js'),
    nodeCmd('tools/checks/library-quick-switcher-v600-smoke.js'),
    nodeCmd('tools/checks/library-user-tags-v600-smoke.js'),
    nodeCmd('tools/checks/library-user-tags-api-v600-smoke.js'),
    nodeCmd('tools/checks/library-tag-facet-v601-smoke.mjs'),
    nodeCmd('tools/checks/library-user-tags-contract-v601-smoke.js'),
    nodeCmd('tools/checks/read-data-user-tags-v601-smoke.mjs'),
    nodeCmd('tools/checks/shared-partial-write-v602-smoke.mjs'),
    nodeCmd('tools/checks/device-state-write-v602-smoke.mjs'),
    nodeCmd('tools/checks/user-state-shelf-cache-v602-smoke.js'),
    nodeCmd('tools/checks/precompressed-negotiation-v602-smoke.js'),
    nodeCmd('tools/checks/service-worker-precache-key-v602-smoke.js'),
    nodeCmd('tools/checks/library-tag-pagination-v602-smoke.js'),
    nodeCmd('tools/checks/library-facet-request-race-v602-smoke.mjs'),
    nodeCmd('tools/checks/library-state-integrity-v602-smoke.js'),
    nodeCmd('tools/checks/metadata-pacing-v600-smoke.js'),
    nodeCmd('tools/checks/mobile-library-v598-smoke.mjs'),
    nodeCmd('tools/checks/mobile-library-structure-v598-smoke.js'),
    nodeCmd('tools/checks/ux-core-v597-smoke.js'),
    ...GROUPS.docs,
    ...GROUPS.cache,
    ...GROUPS.security,
    ...GROUPS.reader,
    ...GROUPS.search,
    ...GROUPS.settings,
    ...GROUPS.server,
    ...GROUPS.frontend,
    ...GROUPS.audit,
    nodeCmd('tools/checks/library-v600-browser-smoke.js'),
    nodeCmd('tools/checks/library-v601-browser-smoke.js'),
    nodeCmd('tools/checks/initial-load-browser-v600-smoke.js')
  ])
});

const ALL_GROUPS = Object.freeze({ ...GROUPS, ...COMPOSITE_GROUPS });

function uniqueTasks(tasks = []) {
  const seen = new Set();
  return tasks.filter((task) => {
    const key = String(task && task.label || '');
    if (!key || seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function printUsage() {
  const groups = Object.keys(ALL_GROUPS).sort().map(name => `  --${name}`).join('\n');
  console.error(`Usage: node tools/run_smoke_tests.js --<group>\n\nGroups:\n${groups}`);
}

function parseGroup(argv) {
  const flags = argv.filter(arg => arg.startsWith('--'));
  if (flags.length !== 1) return null;
  const name = flags[0].slice(2);
  if (!Object.prototype.hasOwnProperty.call(ALL_GROUPS, name)) return null;
  if (argv.some(arg => !arg.startsWith('--'))) return null;
  return name;
}

const packageJson = JSON.parse(require('fs').readFileSync(path.join(root, 'package.json'), 'utf8'));
const declaredPackages = new Set([
  ...Object.keys(packageJson.dependencies || {}),
  ...Object.keys(packageJson.devDependencies || {}),
  ...Object.keys(packageJson.optionalDependencies || {})
]);
function packageRootName(specifier = '') {
  const value = String(specifier || '');
  if (!value || value.startsWith('.') || value.startsWith('/') || value.startsWith('node:')) return '';
  if (value.startsWith('@')) return value.split('/').slice(0, 2).join('/');
  return value.split('/')[0];
}
function classifyBlockedDependency(output = '') {
  const text = String(output || '');
  const match = text.match(/Cannot find (?:module|package) ['\"]([^'\"]+)['\"]/i)
    || text.match(/ERR_MODULE_NOT_FOUND[\s\S]*?package ['\"]([^'\"]+)['\"]/i);
  const packageName = packageRootName(match?.[1] || '');
  if (packageName && declaredPackages.has(packageName)) return { blocked:true, dependency:packageName };
  const playwrightDeclared = [...declaredPackages].some(name => name === 'playwright' || name === '@playwright/test' || name.startsWith('playwright-'));
  if (/Executable doesn't exist|browserType\.launch|Playwright browser/i.test(text) && playwrightDeclared) return { blocked:true, dependency:'playwright-browser' };
  return { blocked:false, dependency:'' };
}
function allowDependencyBlocks() { const raw = String(process.env.SMOKE_ALLOW_DEPENDENCY_BLOCKS || '').trim(); return raw ? !/^(0|false|no|off)$/i.test(raw) : true; }
function failFast() { return /^(1|true|yes|on)$/i.test(String(process.env.SMOKE_FAIL_FAST || '')); }
function resultJsonPath(group) { const configured = String(process.env.SMOKE_RESULT_JSON || '').trim(); return configured ? path.resolve(root, configured) : path.join(root, 'data', 'diagnostics', `smoke-${group}-last.json`); }
function writeResultJson(group, payload) { const target = resultJsonPath(group); const dir = path.dirname(target); const temp = `${target}.${process.pid}.${Date.now()}.tmp`; fs.mkdirSync(dir, { recursive:true }); fs.writeFileSync(temp, JSON.stringify(payload, null, 2)); fs.renameSync(temp, target); return target; }
function commandTimeoutMs() {
  const configured = Number(process.env.SMOKE_COMMAND_TIMEOUT_MS);
  return Number.isFinite(configured) ? Math.max(1000, Math.min(15 * 60 * 1000, configured)) : 120000;
}
function runCommand(task, index, total) {
  console.log(`\n[${index}/${total}] ${task.label}`);
  const effectiveTimeoutMs = commandTimeoutMs();
  const processTreeRunner = path.join(root, 'tools', 'process-tree-runner.js');
  const result = spawnSync(process.execPath, [processTreeRunner, `--cwd=${root}`, `--timeout-ms=${effectiveTimeoutMs}`, '--', task.command, ...task.args], {
    cwd: root,
    env: process.env,
    encoding:'utf8',
    stdio: 'pipe',
    shell: false,
    windowsHide: true,
    timeout:effectiveTimeoutMs + 5000,
    maxBuffer:16 * 1024 * 1024
  });
  const stdout = String(result.stdout || '');
  const stderr = String(result.stderr || '');
  if (stdout) process.stdout.write(stdout);
  if (stderr) process.stderr.write(stderr);
  if (result.error || result.status === 124) {
    return {
      ok:false,
      blocked:false,
      timedOut:result.status === 124 || result.error?.code === 'ETIMEDOUT',
      command:task.label,
      error:result.error?.message || (result.status === 124 ? `command timed out after ${effectiveTimeoutMs}ms` : ''),
      status:result.status
    };
  }
  const combinedOutput = stdout + '\n' + stderr;
  const dependency = classifyBlockedDependency(combinedOutput);
  const explicitStaticOnly = /"staticOnly"\s*:\s*true|"mode"\s*:\s*"static-only"/i.test(combinedOutput);
  const explicitPartial = result.status === 77 && /"(?:partialPass|blocked|blockedCapabilities|blockedDependency|staticOnly|mode)"/.test(combinedOutput);
  const inferredDependencyBlock = result.status !== 0 && dependency.blocked;
  const blocked = explicitStaticOnly || explicitPartial || (inferredDependencyBlock && allowDependencyBlocks());
  return {
    ok: result.status === 0 && !blocked,
    blocked,
    testStrength: explicitStaticOnly ? 'static-only' : blocked ? 'environment-blocked' : 'runtime',
    dependency: dependency.dependency,
    dependencyBlockOptIn: inferredDependencyBlock && allowDependencyBlocks(),
    command: task.label,
    status: result.status
  };
}

function main() {
  const group = parseGroup(process.argv.slice(2));
  if (!group) {
    printUsage();
    process.exit(2);
  }
  const tasks = uniqueTasks(ALL_GROUPS[group]);
  console.log(`Smoke runner group: ${group}`);
  const results = [];
  for (let i = 0; i < tasks.length; i += 1) {
    const result = runCommand(tasks[i], i + 1, tasks.length);
    results.push(result);
    if (!result.ok && !result.blocked && failFast()) break;
  }
  const passed = results.filter(result => result.ok).length;
  const blocked = results.filter(result => result.blocked);
  const failed = results.filter(result => !result.ok && !result.blocked);
  const report = {
    schemaVersion:1,
    group,
    generatedAt:new Date().toISOString(),
    packageVersion:packageJson.version,
    total:tasks.length,
    executed:results.length,
    passed,
    blocked:blocked.length,
    failed:failed.length,
    timedOut:results.filter(result => result.timedOut).length,
    allowDependencyBlocks:allowDependencyBlocks(),
    failFast:failFast(),
    results
  };
  let reportPath = '';
  try { reportPath = writeResultJson(group, report); }
  catch (error) { console.error(`Smoke result JSON write failed: ${error.message || error}`); }
  if (failed.length) {
    console.error(`
Smoke runner failed: ${passed}/${tasks.length}; blocked: ${blocked.length}; failed: ${failed.length}`);
    failed.forEach(item => console.error(`Failed command: ${item.command}${item.error ? ` · ${item.error}` : ''}`));
    if (reportPath) console.error(`Result JSON: ${reportPath}`);
    process.exit(failed[0].status || 1);
  }
  console.log(`
Smoke runner passed: ${passed}/${tasks.length}; blocked: ${blocked.length}`);
  blocked.forEach(result => console.log(`Blocked command: ${result.command}${result.dependency ? ` · missing ${result.dependency}` : ''}`));
  if (reportPath) console.log(`Result JSON: ${reportPath}`);
  process.exit(0);
}

if (typeof require !== 'undefined' && typeof module !== 'undefined' && require.main === module) main();
if (typeof module !== 'undefined') module.exports = { allowDependencyBlocks, failFast, resultJsonPath, writeResultJson, commandTimeoutMs, ALL_GROUPS, uniqueTasks, packageRootName, classifyBlockedDependency, runCommand };
